SIS/force-app/main/default/objects/Intake_Master__c/Intake_Master__c.object-meta.xml
<CustomObject>
    <label>Intake Master</label>
    <nameField>
        <displayFormat>IM-{00000}</displayFormat>
        <label>Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intake Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Intake_Master__c/fields/Programme_Master__c.field-meta.xml
<CustomField>
    <fullName>Programme_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme Master</label>
    <referenceTo>Programme_Master__c</referenceTo>
    <relationshipLabel>Intake Masters</relationshipLabel>
    <relationshipName>Intake_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/Programme_Application__c.object-meta.xml
<CustomObject>
    <label>Programme Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Programme Application No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programme Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Acceptance_Date__c.field-meta.xml
<CustomField>
    <fullName>Acceptance_Date__c</fullName>
    <label>Acceptance Date</label>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Conditional_Code__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Code__c</fullName>
    <label>Conditional Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Immigration_Pass_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Immigration_Pass_Expiry_Date__c</fullName>
    <label>Immigration Pass Expiry Date</label>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Immigration_Pass_Institution_Name__c.field-meta.xml
<CustomField>
    <fullName>Immigration_Pass_Institution_Name__c</fullName>
    <label>Immigration Pass Institution Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Immigration_Pass_Type__c.field-meta.xml
<CustomField>
    <fullName>Immigration_Pass_Type__c</fullName>
    <label>Immigration Pass Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEPENDENT (DIPLOMATIC)</fullName>
            </value>
            <value>
                <fullName>DEPENDENT (EXPATRIATE/EMPLOYMENT)</fullName>
            </value>
            <value>
                <fullName>DEPENDENT (MM2H)</fullName>
            </value>
            <value>
                <fullName>DEPENDENT (RESIDENT PASS TALENT)</fullName>
            </value>
            <value>
                <fullName>DEPENDENT PASS</fullName>
            </value>
            <value>
                <fullName>DIPLOMATIC PASS</fullName>
            </value>
            <value>
                <fullName>EMGS APPROVAL LETTER</fullName>
            </value>
            <value>
                <fullName>EMPLOYMENT PASS</fullName>
            </value>
            <value>
                <fullName>EXEMPTED (MAIN PROGRAMME)</fullName>
            </value>
            <value>
                <fullName>EXEMPTED (MC)</fullName>
            </value>
            <value>
                <fullName>EXEMPTED (ODL)</fullName>
            </value>
            <value>
                <fullName>MALAYSIAN PR</fullName>
            </value>
            <value>
                <fullName>MM2H</fullName>
            </value>
            <value>
                <fullName>PERMISSION TO STUDY</fullName>
            </value>
            <value>
                <fullName>PREVIOUS INSTITUTION STP</fullName>
            </value>
            <value>
                <fullName>RESIDENCE PASS</fullName>
            </value>
            <value>
                <fullName>SOCIAL PASS</fullName>
            </value>
            <value>
                <fullName>SPECIAL PASS</fullName>
            </value>
            <value>
                <fullName>STUDENT PASS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Intake_Master__c.field-meta.xml
<CustomField>
    <fullName>Intake_Master__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Intake Master</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Intake Master record does not belong to the chosen Programme Master.</errorMessage>
        <filterItems>
            <field>Intake_Master__c.Programme_Master__c</field>
            <operation>equals</operation>
            <valueField>$Source.Programme_Master__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Intake_Master__c</referenceTo>
    <relationshipLabel>Programme Applications</relationshipLabel>
    <relationshipName>Programme_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Offer_Letter_Printed_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Letter_Printed_Date__c</fullName>
    <label>Offer Date</label>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending For Approval</fullName>
                <default>true</default>
                <label>Pending For Approval</label>
            </value>
            <value>
                <fullName>Full Offer</fullName>
            </value>
            <value>
                <fullName>Conditional Offer</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Programme_Master__c.field-meta.xml
<CustomField>
    <fullName>Programme_Master__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Programme Master</label>
    <referenceTo>Programme_Master__c</referenceTo>
    <relationshipLabel>Programme Applications</relationshipLabel>
    <relationshipName>Programme_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Programme Applications</relationshipLabel>
    <relationshipName>Programme_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/Programme_Master__c.object-meta.xml
<CustomObject>
    <label>Programme Master</label>
    <nameField>
        <label>Programme Master  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Programme_Master__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Student__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/classes/EMXWebServiceForProgramApplication.cls
@RestResource(urlMapping='/ProgramApplication/*')
global class EMXWebServiceForProgramApplication {
    public class MyException extends Exception {}
    
    @HttpPatch
    global static void updateProgramApplication() {
        Map<String, Object> resultMsg = new Map<String, Object>();
        Map<String, Map<String, Object>> resultMap = new Map<String, Map<String, Object>>();
        RestResponse res = RestContext.response;
        RestRequest req = RestContext.request;
        
        try {
            
            if (req == null || req.requestBody == null) {
                throw new MyException('Invalid request: No request body found.');
            }
            
            String requestBody = req.requestBody.toString();
            System.debug('Request Body: ' + requestBody);
            Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(requestBody);
            System.debug('Parsed Request Map: ' + requestMap);
            
            if (!requestMap.containsKey('programApplication')) {
                throw new MyException('Missing "programApplication" in request payload.');
            }
            
            String programJson = JSON.serialize(requestMap.get('programApplication'));
            System.debug('Program JSON: ' + programJson);
            EMXWebServiceWrapper.programApplication WrapProgram = (EMXWebServiceWrapper.programApplication) JSON.deserialize(programJson, EMXWebServiceWrapper.programApplication.class);
            System.debug('WrapProgram: ' + WrapProgram);
            
            
            if (String.isBlank(WrapProgram.CRMProgramApplicationID)) {
                throw new MyException('CRMProgramApplicationID is mandatory to update. Please enter CRMProgramApplicationID.');
            }
            
            
            
            List<String> missingFields = new List<String>();
            if (String.isBlank(WrapProgram.CRMStudentID)) missingFields.add('CRMStudentID');
            if (String.isBlank(WrapProgram.CRMProgrammeMasterID)) missingFields.add('CRMProgrammeMasterID');
            if (String.isBlank(WrapProgram.CRMIntakeMasterID)) missingFields.add('CRMIntakeMasterID');
            
            
            
            
            if (!missingFields.isEmpty()) {
                
                throw new MyException('The required field(s) are missing: ' + String.join(missingFields, ', '));
            }
            
            
            List<Student__c> std = [SELECT Id FROM Student__c WHERE Id = :WrapProgram.CRMStudentID LIMIT 1];
            List<Programme_Master__c> pMaster = [SELECT Id FROM Programme_Master__c WHERE Id = :WrapProgram.CRMProgrammeMasterID LIMIT 1];
            List<Intake_Master__c> iMaster = [SELECT Id, Programme_Master__r.Id 
                                              FROM Intake_Master__c 
                                              WHERE Id = :WrapProgram.CRMIntakeMasterID 
                                              AND Programme_Master__r.Id = :WrapProgram.CRMProgrammeMasterID 
                                              LIMIT 1];
            
            
            List<String> missingRecords = new List<String>();
            if (std.isEmpty()) missingRecords.add('CRMStudentID');
            if (pMaster.isEmpty()) missingRecords.add('CRMProgrammeMasterID');
            if (iMaster.isEmpty()) missingRecords.add('CRMIntakeMasterID');
            
            if (!missingRecords.isEmpty()) {
                String errorMessage = 'No record found with the provided: ' + String.join(missingRecords, ', ');
                if (missingRecords.contains('CRMIntakeMasterID')) {
                    errorMessage +='.  Please ensure that the provided CRMIntakeMasterID is correct and is linked to CRMProgrammeMasterID.';
                } 
                throw new MyException(errorMessage);
            }
            
            Map<String, String> dateFields = new Map<String, String>{
                'offerDate' => WrapProgram.offerDate,
                    'acceptanceDate' => WrapProgram.acceptanceDate,
                    'immigrationPassExpiryDate' => WrapProgram.immigrationPassExpiryDate
                    };
                        
                        
                        for (String fieldName : dateFields.keySet()) {
                            String dateValue = dateFields.get(fieldName);
                            if (String.isNotBlank(dateValue) && !Pattern.matches('^\\d{4}-\\d{1,2}-\\d{1,2}$', dateValue)) {
                                throw new MyException('Invalid Date Format for ' + fieldName + '. Please enter yyyy-MM-dd format.');
                            }
                        }
            
            
            
            
            
            List<Programme_Application__c> applicationData = [SELECT Id,EMX_ID__c, Offer_Status__c, Conditional_Code__c, 
                                                              Offer_Letter_Printed_Date__c, Acceptance_Date__c, 
                                                              Immigration_Pass_Type__c, Immigration_Pass_Expiry_Date__c, 
                                                              Immigration_Pass_Institution_Name__c, Student__c, 
                                                              Programme_Master__c, Intake_Master__c
                                                              FROM Programme_Application__c 
                                                              WHERE Id = :WrapProgram.CRMProgramApplicationID 
                                                              LIMIT 1];
            
            if (applicationData.isEmpty()) {
                throw new MyException('No matching Program Application record found.');
            }
            
            Programme_Application__c application = applicationData[0];
            
            
            application.Offer_Status__c = String.isNotBlank(WrapProgram.offerStatus) ? WrapProgram.offerStatus : application.Offer_Status__c;
            application.EMX_ID__c =String.isNotBlank(WrapProgram.EMXID)?WrapProgram.EMXID : application.EMX_ID__c;
            application.Conditional_Code__c = String.isNotBlank(WrapProgram.conditionalCode) ? WrapProgram.conditionalCode : application.Conditional_Code__c;
            application.Offer_Letter_Printed_Date__c = String.isNotBlank(WrapProgram.offerDate) ? Date.valueOf(WrapProgram.offerDate) : application.Offer_Letter_Printed_Date__c;
            application.Acceptance_Date__c = String.isNotBlank(WrapProgram.acceptanceDate) ? Date.valueOf(WrapProgram.acceptanceDate) : application.Acceptance_Date__c;
            application.Immigration_Pass_Type__c = String.isNotBlank(WrapProgram.immigrationPassType) ? WrapProgram.immigrationPassType : application.Immigration_Pass_Type__c;
            application.Immigration_Pass_Expiry_Date__c = String.isNotBlank(WrapProgram.immigrationPassExpiryDate) ? Date.valueOf(WrapProgram.immigrationPassExpiryDate) : application.Immigration_Pass_Expiry_Date__c;
            application.Immigration_Pass_Institution_Name__c = String.isNotBlank(WrapProgram.immigrationPassInstitutionName) ? WrapProgram.immigrationPassInstitutionName : application.Immigration_Pass_Institution_Name__c;         
            application.Student__c = std[0].Id;
            application.Programme_Master__c = pMaster[0].Id;
            application.Intake_Master__c = iMaster[0].Id;
            
            update application;
            System.debug('Program Application data updated successfully');
            
            res.statusCode = 200;
           // WrapProgram.programApplicationId=application.Id;
            WrapProgram.programApplicationStatus='Program Application record updated successfully.';
            //resultMsg.put('message', 'Program Application record updated successfully.');
            resultMsg.put('body', WrapProgram);
            //resultMsg.put('programId', application.Id);
            resultMap.put('status', resultMsg);
            String responseBody = JSON.serialize(resultMap);
            res.responseBody = Blob.valueOf(responseBody);
            SISIntegrationLog.createLog(req.requestBody.toString(),responseBody,'Success');
            
        } catch (MyException e) {
            System.debug('Error: ' + e.getStackTraceString());
            res.statusCode = 400;
            resultMsg.put('programApplicationStatus', e.getMessage());
            resultMap.put('status', resultMsg);
            String responseBody = JSON.serialize(resultMap);
            res.responseBody = Blob.valueOf(responseBody);
            SISIntegrationLog.createLog(req.requestBody.toString(),responseBody,'Failure');
        }catch (Exception e) {
            System.debug('Error---'+ e.getStackTraceString());
            res.statusCode = 400;
            resultMsg.put('programApplicationStatus',string.valueOf(e.getMessage()));
            resultMap.put('status',resultMsg);
            String responseBody = JSON.serialize(resultMap);
            res.responseBody = Blob.valueOf(responseBody);
            SISIntegrationLog.createLog(req.requestBody.toString(),responseBody,'Failure');
        }
        
        //res.responseBody = Blob.valueOf(JSON.serialize(resultMap));
        System.debug('Response Body: ' + res.responseBody.toString());
    }
    
}