SIS/force-app/main/default/objects/Account/recordTypes/Campus_ID.recordType-meta.xml
<RecordType>
    <fullName>Campus_ID</fullName>
    <active>true</active>
    <label>Campus ID</label>
</RecordType>

SIS/force-app/main/default/objects/Intake_Master__c/Intake_Master__c.object-meta.xml
<CustomObject>
    <label>Intake Master</label>
    <nameField>
        <displayFormat>IM-{00000}</displayFormat>
        <label>Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intake Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Intake_Master__c/fields/Application_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Application_Allowed__c</fullName>
    <label>Application Allowed</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Intake_Master__c/fields/Course_Detail_Intake_ID__c.field-meta.xml
<CustomField>
    <fullName>Course_Detail_Intake_ID__c</fullName>
    <label>Course Detail Intake ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SIS/force-app/main/default/objects/Intake_Master__c/fields/Intake_Number__c.field-meta.xml
<CustomField>
    <fullName>Intake_Number__c</fullName>
    <label>Intake Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Intake_Master__c/fields/Programme_Master__c.field-meta.xml
<CustomField>
    <fullName>Programme_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme Master</label>
    <referenceTo>Programme_Master__c</referenceTo>
    <relationshipLabel>Intake Masters</relationshipLabel>
    <relationshipName>Intake_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Intake_Master__c/fields/Study_Mode__c.field-meta.xml
<CustomField>
    <fullName>Study_Mode__c</fullName>
    <label>Study Mode</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/Programme_Master__c.object-meta.xml
<CustomObject>
    <label>Programme Master</label>
    <nameField>
        <label>Programme Master  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Campus_Code__c.field-meta.xml
<CustomField>
    <fullName>Campus_Code__c</fullName>
    <label>Campus Code</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Campus_Location__c.field-meta.xml
<CustomField>
    <fullName>Campus_Location__c</fullName>
    <label>Campus Location</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Campus_Name__c.field-meta.xml
<CustomField>
    <fullName>Campus_Name__c</fullName>
    <label>Campus Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Campus_SFID__c.field-meta.xml
<CustomField>
    <fullName>Campus_SFID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campus SFID</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please Select a Valid Campus</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Campus_ID</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programme Masters</relationshipLabel>
    <relationshipName>Programme_Masters</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Is_Offer__c.field-meta.xml
<CustomField>
    <fullName>Is_Offer__c</fullName>
    <label>Is Offer</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Level_of_Education__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Education__c</fullName>
    <label>Level of Education</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Programme_Code__c.field-meta.xml
<CustomField>
    <fullName>Programme_Code__c</fullName>
    <label>Programme Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Programme_Duration__c.field-meta.xml
<CustomField>
    <fullName>Programme_Duration__c</fullName>
    <label>Programme Duration</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/School_Code__c.field-meta.xml
<CustomField>
    <fullName>School_Code__c</fullName>
    <label>School Code</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/classes/SISProgrammeAndIntakeMasterHandlerTest.cls
@isTest
public with sharing class SISProgrammeAndIntakeMasterHandlerTest {
    @testSetup
    public static void setUpData(){
        // Create Campus
        List<RecordType> rt = new List<RecordType>();
        rt = [Select Id From RecordType Where DeveloperName = 'Campus_ID' LIMIT 1];
        
        Account acc = new Account();
        acc.RecordTypeId = rt[0].Id;
        acc.Name = 'SISJ';
        insert acc;
        
        //Programme Master
        Programme_Master__c pMaster = new Programme_Master__c();
        pMaster.Name = 'TesTPM';
        pMaster.Programme_Code__c = '123';
        pMaster.Programme_Duration__c = 12;
        pMaster.Level_of_Education__c = 'Primary';
        pMaster.Is_Offer__c = 'y';
        pMaster.Campus_SFID__c = acc.Id;
        pMaster.Campus_Code__c = 'SIS123';
        pMaster.Campus_Name__c = 'SIS';
        pMaster.Campus_Location__c = 'malaysia';
        pMaster.School_Code__c = 'SIS789';
        insert pMaster;
        
        //Intake Master
        Intake_Master__c iMaster = new Intake_Master__c();
        iMaster.Programme_Master__c = pMaster.Id;
        iMaster.EMX_ID__c = '159159';
        iMaster.Intake_Number__c = '789456123';
        iMaster.Study_Mode__c = 'Online';
        iMaster.Course_Detail_Intake_ID__c = 123987;
        iMaster.Application_Allowed__c = 'YES';
        insert iMaster;
    }
    
    @isTest
    public static void handleProgrammeAndIntakeMasterTestWithoutSFID(){
        Account acc = [Select Id From Account Where RecordType.DeveloperName = 'Campus_ID' LIMIT 1];
            
        Map<String, Object> programmeMaster = new Map<String, Object>();
        programmeMaster.put('CRMProgrammeMasterID', '');
        programmeMaster.put('EMXID', '24680');
        programmeMaster.put('programCode', 'SCISY10');
        programmeMaster.put('programmeName', 'India International after Validate PM');
        programmeMaster.put('programmeDuration', '10');
        programmeMaster.put('levelOfEducation', 'Secondary School');
        programmeMaster.put('isOffer', 'Y');
        programmeMaster.put('CRMCampusID', acc.Id);
        programmeMaster.put('campusCode', 'SISCKL');
        programmeMaster.put('campusName', 'Sunway City International School');
        programmeMaster.put('campusLocation', 'Sunway City');
        programmeMaster.put('schoolCode', 'SCIS');
        programmeMaster.put('schoolName', 'school name');
        programmeMaster.put('departmentName', 'department name');
        programmeMaster.put('departmentCode', 'department code');
        
        Map<String, Object> intakeMasterItem = new Map<String, Object>();
        intakeMasterItem.put('CRMIntakeMasterID', '');
        intakeMasterItem.put('EMXID', '13579');
        intakeMasterItem.put('intakeNumber', '555555');
        intakeMasterItem.put('studyMode', 'Online');
        intakeMasterItem.put('courseDetailIntakeID', '55555');
        intakeMasterItem.put('applicationAllowed', 'YES');
        intakeMasterItem.put('CRMProgrammeMasterID', '');
        
        List<Map<String, Object>> intakeMasterList = new List<Map<String, Object>>();
        intakeMasterList.add(intakeMasterItem);
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('programmeMaster', programmeMaster);
        requestBodyMap.put('intakeMaster', intakeMasterList);
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        // Mocking request and response
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        
        SISProgrammeAndIntakeMasterHandler.handleProgrammeAndIntakeMaster();
        Test.stopTest();
    }
    
    @isTest
    public static void handleProgrammeAndIntakeMasterTestWithSFID(){
        String pm = [SELECT Id FROM Programme_Master__c WHERE Name = 'TesTPM' LIMIT 1].Id;
        String im = [SELECT Id FROM Intake_Master__c WHERE EMX_ID__c = '159159' LIMIT 1].Id;
        Account acc = [Select Id From Account Where RecordType.DeveloperName = 'Campus_ID' LIMIT 1];
        
        Map<String, Object> programmeMaster = new Map<String, Object>();
        programmeMaster.put('CRMProgrammeMasterID', pm);
        programmeMaster.put('EMXID', '24680');
        programmeMaster.put('programCode', 'SCISY10');
        programmeMaster.put('programmeName', 'India International after Validate PM');
        programmeMaster.put('programmeDuration', '10');
        programmeMaster.put('levelOfEducation', 'Secondary School');
        programmeMaster.put('isOffer', 'Y');
        programmeMaster.put('CRMCampusID', acc.Id);
        programmeMaster.put('campusCode', 'SISCKL');
        programmeMaster.put('campusName', 'Sunway City International School');
        programmeMaster.put('campusLocation', 'Sunway City');
        programmeMaster.put('schoolCode', 'SCIS');
        programmeMaster.put('schoolName', 'school name');
        programmeMaster.put('departmentName', 'department name');
        programmeMaster.put('departmentCode', 'department code');
        
        Map<String, Object> intakeMasterItem = new Map<String, Object>();
        intakeMasterItem.put('CRMIntakeMasterID', im);
        intakeMasterItem.put('EMXID', '13579');
        intakeMasterItem.put('intakeNumber', '555555');
        intakeMasterItem.put('studyMode', 'Online');
        intakeMasterItem.put('courseDetailIntakeID', '55555');
        intakeMasterItem.put('applicationAllowed', 'YES');
        intakeMasterItem.put('CRMProgrammeMasterID', pm);
        
        List<Map<String, Object>> intakeMasterList = new List<Map<String, Object>>();
        intakeMasterList.add(intakeMasterItem);
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('programmeMaster', programmeMaster);
        requestBodyMap.put('intakeMaster', intakeMasterList);
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        // Mocking request and response
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        
        SISProgrammeAndIntakeMasterHandler.handleProgrammeAndIntakeMaster();
        Test.stopTest();
    }
    
    
    @isTest
    public static void missingFieldInProgramMaster(){
        String pm = [SELECT Id FROM Programme_Master__c WHERE Name = 'TesTPM' LIMIT 1].Id;
        String im = [SELECT Id FROM Intake_Master__c WHERE EMX_ID__c = '159159' LIMIT 1].Id;
        
        Map<String, Object> programmeMaster = new Map<String, Object>();
        programmeMaster.put('CRMProgrammeMasterID', pm);
        programmeMaster.put('EMXID', '24680');
        programmeMaster.put('programCode', '');
        programmeMaster.put('programmeName', '');
        programmeMaster.put('programmeDuration', '');
        programmeMaster.put('levelOfEducation', '');
        programmeMaster.put('isOffer', '');
        programmeMaster.put('CRMCampusID', '');
        programmeMaster.put('campusCode', '');
        programmeMaster.put('campusName', '');
        programmeMaster.put('campusLocation', 'Sunway City');
        programmeMaster.put('schoolCode', '');
        programmeMaster.put('schoolName', '');
    
        
        Map<String, Object> intakeMasterItem = new Map<String, Object>();
        intakeMasterItem.put('CRMIntakeMasterID', im);
        intakeMasterItem.put('EMXID', '13579');
        intakeMasterItem.put('intakeNumber', '555555');
        intakeMasterItem.put('studyMode', 'Online');
        intakeMasterItem.put('courseDetailIntakeID', '55555');
        intakeMasterItem.put('applicationAllowed', 'YES');
        intakeMasterItem.put('CRMProgrammeMasterID', pm);
        
        List<Map<String, Object>> intakeMasterList = new List<Map<String, Object>>();
        intakeMasterList.add(intakeMasterItem);
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('programmeMaster', programmeMaster);
        requestBodyMap.put('intakeMaster', intakeMasterList);
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        // Mocking request and response
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        
        SISProgrammeAndIntakeMasterHandler.handleProgrammeAndIntakeMaster();
        Test.stopTest();
    }
    
}