SIS/force-app/main/default/objects/Lead/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Parent_Lead__c.field-meta.xml
<CustomField>
    <fullName>Parent_Lead__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Lead</label>
    <referenceTo>Parent_Lead__c</referenceTo>
    <relationshipLabel>Child Leads</relationshipLabel>
    <relationshipName>Child_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Passport_IC__c.field-meta.xml
<CustomField>
    <fullName>Passport_IC__c</fullName>
    <label>Passport/ IC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/Parent_Lead__c.object-meta.xml
<CustomObject>
    <label>Parent Lead</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parent Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Campus__c.field-meta.xml
<CustomField>
    <fullName>Campus__c</fullName>
    <label>Campus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SISKL</fullName>
            </value>
            <value>
                <fullName>SISJB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Mobile_Number_1__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_1__c</fullName>
    <label>Mobile Number 1</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Parent_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship__c</fullName>
    <label>Parent Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunty</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Passport_IC__c.field-meta.xml
<CustomField>
    <fullName>Passport_IC__c</fullName>
    <label>Passport/ IC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/RoundRobinSetting__c/RoundRobinSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RoundRobinSetting</label>
</CustomObject>

SIS/force-app/main/default/objects/RoundRobinSetting__c/fields/Last_Assigned_Index__c.field-meta.xml
<CustomField>
    <fullName>Last_Assigned_Index__c</fullName>
    <label>Last_Assigned_Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SIS/force-app/main/default/classes/SIS_LeadAssignmentRoundRobinTest.cls
@isTest
public with sharing class SIS_LeadAssignmentRoundRobinTest {
    @testSetup
    public static void setUpData() {
        // Create a test user to assign leads
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Admin' LIMIT 1];
        User testUser = new User();
        testUser.LastName = 'testuser';
        testUser.Alias = 'testuser';
        testUser.Email = 'testuserforroundrobin@example.com';
        testUser.UserName = uniqueUserName;
        testUser.ProfileId = p.Id;
        testUser.TimeZoneSidKey = 'Asia/Singapore';
        testUser.LocaleSidKey = 'en_SG';
        testUser.EmailEncodingKey = 'UTF-8';
        testUser.LanguageLocaleKey = 'en_US';
        
        insert testUser;
        
        
        //Create Parent Lead
        Parent_Lead__c pl = new Parent_Lead__c();
        pl.Name = 'TestParentLead1';
        pl.Campus__c = 'SIS';
        pl.Email__c = 'test12345test@gmail.com';
        pl.Mobile_Number_1__c = '4863257895';
        pl.Passport_IC__c = '112233445576';
        pl.Parent_Relationship__c = 'Father';
        insert pl;
        
        //Child Lead with parent lead
        Lead l = new Lead();
        l.LastName = 'testchildLead';
        l.Status = 'New';
        l.Date_of_Birth__c = Date.today()-1;
        l.Parent_Lead__c = pl.Id;
        l.Passport_IC__c = '123122121123';
        l.Nationality__c = 'MY';
        insert l;
        
        Lead le = new Lead();
        le.LastName = 'testchildLeadForNonCitizen';
        le.Status = 'New';
        le.Date_of_Birth__c = Date.today()-5;
        le.Parent_Lead__c = pl.Id;
        le.Passport_IC__c = '123222111123';
        le.Nationality__c = 'IN';
        insert le;
        
        SIS_LeadAssignmentRoundRobinTest.futureMethodForSetUpObjects();
    }
    
    @future
    public static void futureMethodForSetUpObjects(){
        User testUser = [SELECT Id FROM User WHERE LastName = 'testuser' LIMIT 1];
        
        RoundRobinSetting__c rrs = new RoundRobinSetting__c();
        rrs.Name = 'SIS_Lead Assignment For RR';
        rrs.Last_Assigned_Index__c = 5;
        
        insert rrs;
        
    }
    
    @isTest
    public static void assignLead(){
        List<Lead> leadListForMY = [SELECT Id, Nationality__c, FirstName, LastName FROM Lead WHERE LastName = 'testchildLead' LIMIT 1];
        List<Lead> leadListForNonMY = [SELECT Id, Nationality__c, FirstName, LastName FROM Lead WHERE LastName = 'testchildLeadForNonCitizen' LIMIT 1];
        Test.startTest();
        SIS_LeadAssignmentRoundRobin.assignLead(leadListForMY);
        SIS_LeadAssignmentRoundRobin.assignLead(leadListForNonMY);
        Test.stopTest();
    }
}