SIS/force-app/main/default/objects/SIS_Integration_log__c/SIS_Integration_log__c.object-meta.xml
<CustomObject>
    <label>SIS Integration Log</label>
    <nameField>
        <displayFormat>SIS log-{0000}</displayFormat>
        <label>SIS Integration log No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SIS Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/SIS_Integration_log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

SIS/force-app/main/default/objects/SIS_Integration_log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

SIS/force-app/main/default/objects/SIS_Integration_log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/classes/SISIntegrationLog.cls
public class SISIntegrationLog {
    public static void createLog(String requestBody, String responseBody, String status) {
        try {
            SIS_Integration_log__c log = new SIS_Integration_log__c();
            
            log.Request_Body__c = (requestBody != null && requestBody.length() > 131072)
                ? requestBody.substring(0, 131072) + '... [More]' : requestBody;
            
            log.Response_Body__c = (responseBody != null && responseBody.length() > 131072)
                ? responseBody.substring(0, 131072) + '... [More]' : responseBody;
            
            log.Status__c = status;
            
            insert log;
            System.debug('Integration log saved successfully');
        } catch (Exception e) {
            System.debug('Error while logging integration: ' + e.getMessage());
        }
    }
    
}