Manufactoring/force-app/main/default/objects/Lead/fields/mfg_CIN__c.field-meta.xml
<CustomField>
    <fullName>mfg_CIN__c</fullName>
    <inlineHelpText>Corporate Identification Number - A 21-character alphanumeric code issued by the Registrar of Companies (ROC) in India under the Companies Act, 2013. It identifies Indian-registered companies.</inlineHelpText>
    <label>CIN</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

Manufactoring/force-app/main/default/objects/Lead/fields/mfg_Communication_Preference__c.field-meta.xml
<CustomField>
    <fullName>mfg_Communication_Preference__c</fullName>
    <label>Communication Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>In-Person Meeting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Lead/fields/mfg_CompanyContactEmail__c.field-meta.xml
<CustomField>
    <fullName>mfg_CompanyContactEmail__c</fullName>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

Manufactoring/force-app/main/default/objects/Lead/fields/mfg_CompanyContactRole__c.field-meta.xml
<CustomField>
    <fullName>mfg_CompanyContactRole__c</fullName>
    <label>Company Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Owner / Director</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Accounts Manager</fullName>
            </value>
            <value>
                <fullName>Service Manager</fullName>
            </value>
            <value>
                <fullName>Engineer / Technical Lead</fullName>
            </value>
            <value>
                <fullName>Finance Head</fullName>
            </value>
            <value>
                <fullName>Operations Head</fullName>
            </value>
            <value>
                <fullName>Logistics Coordinator</fullName>
            </value>
            <value>
                <fullName>Procurement Officer</fullName>
            </value>
            <value>
                <fullName>Admin / Coordinator</fullName>
            </value>
            <value>
                <fullName>Consultant / Advisor</fullName>
            </value>
            <value>
                <fullName>End User / Operator</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Lead/fields/mfg_CreateUser__c.field-meta.xml
<CustomField>
    <fullName>mfg_CreateUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create User</label>
    <type>Checkbox</type>
</CustomField>

Manufactoring/force-app/main/default/objects/Lead/fields/mfg_EstimatedBudget__c.field-meta.xml
<CustomField>
    <fullName>mfg_EstimatedBudget__c</fullName>
    <label>Estimated Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Lead/fields/mfg_ExpectedPurchaseDate__c.field-meta.xml
<CustomField>
    <fullName>mfg_ExpectedPurchaseDate__c</fullName>
    <label>Expected Purchase Date</label>
    <type>Date</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Lead/fields/mfg_GST_Tax_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>mfg_GST_Tax_Registration_Number__c</fullName>
    <label>GST / Tax Registration Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Manufactoring/force-app/main/default/objects/Lead/fields/mfg_KeyRequirementsNotes__c.field-meta.xml
<CustomField>
    <fullName>mfg_KeyRequirementsNotes__c</fullName>
    <inlineHelpText>Capture key insights, customer pain points, or evaluation notes.Any technical or business requirements for the product/service.</inlineHelpText>
    <label>Key Requirements / Notes</label>
    <type>TextArea</type>
</CustomField>

Manufactoring/force-app/main/default/objects/Lead/fields/mfg_Logistics_Support__c.field-meta.xml
<CustomField>
    <fullName>mfg_Logistics_Support__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Logistics Support</label>
    <type>Checkbox</type>
</CustomField>

Manufactoring/force-app/main/default/objects/Lead/fields/mfg_NumberOfOutlets__c.field-meta.xml
<CustomField>
    <fullName>mfg_NumberOfOutlets__c</fullName>
    <label>Number of Outlets</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Lead/fields/mfg_PlanningToBuy__c.field-meta.xml
<CustomField>
    <fullName>mfg_PlanningToBuy__c</fullName>
    <label>PlanningToBuy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Immediately (Within 1 Month)</fullName>
            </value>
            <value>
                <fullName>Short Term (1-3 Months)</fullName>
            </value>
            <value>
                <fullName>Medium Term (3-6 Months)</fullName>
            </value>
            <value>
                <fullName>Long Term (6-12 Months)</fullName>
            </value>
            <value>
                <fullName>Future Plan (Beyond 1 Year)</fullName>
            </value>
            <value>
                <fullName>Still Exploring/No Specific Timeline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Manufactoring/force-app/main/default/objects/Lead/fields/mfg_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>mfg_Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>mfg_Product_Family</valueSetName>
    </valueSet>
</CustomField>

Manufactoring/force-app/main/default/objects/Lead/fields/mfg_Product_Subcategory__c.field-meta.xml
<CustomField>
    <fullName>mfg_Product_Subcategory__c</fullName>
    <label>Product Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>mfg_Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>mfg_Product_Subcategory</valueSetName>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Lead/fields/mfg_Quantity__c.field-meta.xml
<CustomField>
    <fullName>mfg_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Lead/fields/mfg_Urgency_Level__c.field-meta.xml
<CustomField>
    <fullName>mfg_Urgency_Level__c</fullName>
    <label>Urgency Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Lead/fields/mfg_Years_in_Business__c.field-meta.xml
<CustomField>
    <fullName>mfg_Years_in_Business__c</fullName>
    <description>Delaer&apos;s Experience in Years</description>
    <inlineHelpText>In Years</inlineHelpText>
    <label>Years in Business</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Manufactoring/force-app/main/default/globalValueSets/mfg_Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commercial Vehicles</fullName>
    </customValue>
    <customValue>
        <fullName>Compact Sedans</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Vehicles</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchbacks</fullName>
    </customValue>
    <customValue>
        <fullName>SUVs And Crossovers</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

Manufactoring/force-app/main/default/globalValueSets/mfg_Product_Subcategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Battery And Power Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Body And Trim</fullName>
    </customValue>
    <customValue>
        <fullName>Braking System</fullName>
    </customValue>
    <customValue>
        <fullName>Cab And Frame</fullName>
    </customValue>
    <customValue>
        <fullName>Chassis And Suspension</fullName>
    </customValue>
    <customValue>
        <fullName>Drivetrain</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical And Lighting</fullName>
    </customValue>
    <customValue>
        <fullName>Engine Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Exterior Components</fullName>
    </customValue>
    <customValue>
        <fullName>Fuel And Exhaust</fullName>
    </customValue>
    <customValue>
        <fullName>Infotainment</fullName>
    </customValue>
    <customValue>
        <fullName>Interior And Infotainment</fullName>
    </customValue>
    <customValue>
        <fullName>Interior Components</fullName>
    </customValue>
    <customValue>
        <fullName>Lightweight Body</fullName>
    </customValue>
    <customValue>
        <fullName>Motor And Controller</fullName>
    </customValue>
    <customValue>
        <fullName>Powertrain</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Components</fullName>
    </customValue>
    <customValue>
        <fullName>Thermal And Cooling</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical And Electronics</fullName>
        <isActive>false</isActive>
        <label>Electrical And Electronics</label>
    </customValue>
    <masterLabel>Product Subcategory</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

Manufactoring/force-app/main/default/classes/mfg_LeadHandler.cls
public with sharing class mfg_LeadHandler {
      public static void afterUpdate(List<Lead> newList, List<Lead> oldList) {
        List<Lead> leadsToConvert = new List<Lead>();

        for (Integer i = 0; i < newList.size(); i++) {
            Lead newLead = newList[i];
            Lead oldLead = oldList[i];
           System.debug('oldLead.IsConverted: ' + oldLead.IsConverted + ' newLead.IsConverted: ' + newLead.IsConverted + ' newLead.Status:'+newLead.Status);
            if (!oldLead.IsConverted && !newLead.IsConverted && newLead.Status == 'Converted') {
                leadsToConvert.add(newLead);
            }
        }

        if (!leadsToConvert.isEmpty()) {
             //Map<String, Map<String, Object>> finalConversion =leadConvert(leadsToConvert);
             //System.debug('finalConversion: ' + finalConversion);
        }
      }
      
       @AuraEnabled
      public static Map<String, Map<String, Object>> getLead(List<String> leadIds){
         List<Lead> leadsToConvert = new List<Lead>();
                    List<String> leadFields = new List<String>{
            'Id','RecordTypeId','Company','Industry','MobilePhone','OwnerId',
            'LeadSource','AnnualRevenue','NumberOfEmployees','Website','Phone',
            'mfg_CIN__c','mfg_NumberOfOutlets__c','mfg_Years_in_Business__c',
            'mfg_CompanyContactEmail__c','Street','City','State','PostalCode','Country',
            'mfg_CompanyContactRole__c','mfg_PartnerAgreementIssued__c','Rating',
            'mfg_GST_Tax_Registration_Number__c','mfg_Logistics_Support__c',
            'mfg_Inventory_Capacity__c',
            'FirstName','LastName','Email','mfg_Communication_Preference__c',
            'mfg_Address__Street__s','mfg_Address__City__s','mfg_Address__CountryCode__s',
            'mfg_Address__StateCode__s','mfg_Address__PostalCode__s','mfg_CreateUser__c',
            'mfg_Product_Family__c','mfg_EstimatedBudget__c','mfg_Quantity__c','mfg_Product_Subcategory__c',
            'mfg_PlanningToBuy__c','mfg_Urgency_Level__c','mfg_KeyRequirementsNotes__c',
            'mfg_ExpectedPurchaseDate__c'
            };

            //String query = 'SELECT ' + String.join(leadFields, ',') + ' FROM Lead WHERE Id IN :leadIds';
              String query ='SELECT ' + String.join(leadFields, ',') +
                            ', (SELECT Id, CampaignId FROM CampaignMembers WHERE Campaign.IsActive = true)' +
                            ' FROM Lead WHERE Id IN :leadIds';
            leadsToConvert = Database.query(query);
         if (!leadsToConvert.isEmpty()) {
             Map<String, Map<String, Object>> finalMapping = leadConvert(leadsToConvert);
            return finalMapping;
        }
        return null;

      }

       public static Map<String, Map<String, Object>> leadConvert(List<Lead> leadsToConvert){
           return MFG_LeadConversion.convertLeads(leadsToConvert);

      }
    


}