MFG Ready Version/force-app/main/default/objects/mfg_Product_Service_Term__c/mfg_Product_Service_Term__c.object-meta.xml
<CustomObject>
    <label>Product Service Term</label>
    <nameField>
        <displayFormat>PST-{0000000000}</displayFormat>
        <label>Product Service Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Service Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MFG Ready Version/force-app/main/default/objects/mfg_Product_Service_Term__c/fields/mfg_Covered_Product__c.field-meta.xml
<CustomField>
    <fullName>mfg_Covered_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Covered Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Service Terms</relationshipLabel>
    <relationshipName>Product_Service_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Product_Service_Term__c/fields/mfg_Service_Level__c.field-meta.xml
<CustomField>
    <fullName>mfg_Service_Level__c</fullName>
    <label>Service Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Subcategory</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Product_Service_Term__c/fields/mfg_Service_Term__c.field-meta.xml
<CustomField>
    <fullName>mfg_Service_Term__c</fullName>
    <label>Service Term</label>
    <referenceTo>mfg_Service_Term__c</referenceTo>
    <relationshipLabel>Product Service Terms</relationshipLabel>
    <relationshipName>Product_Service_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/mfg_Service_Term__c.object-meta.xml
<CustomObject>
    <label>Service Term</label>
    <nameField>
        <label>Service Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Active__c.field-meta.xml
<CustomField>
    <fullName>mfg_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Covered_Product__c.field-meta.xml
<CustomField>
    <fullName>mfg_Covered_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Covered Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Terms</relationshipLabel>
    <relationshipName>Service_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Expense_Coverage__c.field-meta.xml
<CustomField>
    <fullName>mfg_Expense_Coverage__c</fullName>
    <label>Expense Coverage %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Labor_Coverage__c.field-meta.xml
<CustomField>
    <fullName>mfg_Labor_Coverage__c</fullName>
    <label>Labor Coverage %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Parts_Coverage__c.field-meta.xml
<CustomField>
    <fullName>mfg_Parts_Coverage__c</fullName>
    <label>Parts Coverage %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Service_Level__c.field-meta.xml
<CustomField>
    <fullName>mfg_Service_Level__c</fullName>
    <label>Service Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Subcategory</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Service_Scope_Value__c.field-meta.xml
<CustomField>
    <fullName>mfg_Service_Scope_Value__c</fullName>
    <label>Service Scope Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Service_Unit__c.field-meta.xml
<CustomField>
    <fullName>mfg_Service_Unit__c</fullName>
    <label>Service Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Product2/fields/mfg_Product_Subcategory__c.field-meta.xml
<CustomField>
    <fullName>mfg_Product_Subcategory__c</fullName>
    <label>Product Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetName>mfg_Product_Subcategory</valueSetName>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/globalValueSets/mfg_Product_Subcategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Anti-Diabetics</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Fungal</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Infective</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>Hematology</fullName>
    </customValue>
    <customValue>
        <fullName>Immunosuppressants</fullName>
    </customValue>
    <customValue>
        <fullName>Multiple Sclerosis</fullName>
    </customValue>
    <customValue>
        <fullName>Neurology</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology</fullName>
    </customValue>
    <customValue>
        <fullName>Battery And Power Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Body And Trim</fullName>
    </customValue>
    <customValue>
        <fullName>Braking System</fullName>
    </customValue>
    <customValue>
        <fullName>Cab And Frame</fullName>
    </customValue>
    <customValue>
        <fullName>Chassis And Suspension</fullName>
    </customValue>
    <customValue>
        <fullName>Drivetrain</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical And Lighting</fullName>
    </customValue>
    <customValue>
        <fullName>Engine Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Exterior Components</fullName>
    </customValue>
    <customValue>
        <fullName>Fuel And Exhaust</fullName>
    </customValue>
    <customValue>
        <fullName>Infotainment</fullName>
    </customValue>
    <customValue>
        <fullName>Interior And Infotainment</fullName>
    </customValue>
    <customValue>
        <fullName>Interior Components</fullName>
    </customValue>
    <customValue>
        <fullName>Lightweight Body</fullName>
    </customValue>
    <customValue>
        <fullName>Motor And Controller</fullName>
    </customValue>
    <customValue>
        <fullName>Powertrain</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Components</fullName>
    </customValue>
    <customValue>
        <fullName>Thermal And Cooling</fullName>
    </customValue>
    <masterLabel>Product Subcategory</masterLabel>
</GlobalValueSet>

MFG Ready Version/force-app/main/default/classes/MFG_ServiceTermHandler.cls
public without sharing class MFG_ServiceTermHandler {

    public static void handleNewProducts(List<Product2> newProducts) {
        try {
            if (newProducts == null || newProducts.isEmpty()) {
                return;
            }

            Map<String, mfg_Service_Term__c> productFamily = new Map<String, mfg_Service_Term__c>();
            Map<String, mfg_Service_Term__c> productSubCategory = new Map<String, mfg_Service_Term__c>();
            Map<String, mfg_Service_Term__c> mainProduct = new Map<String, mfg_Service_Term__c>();

            existingServiceTerms(productFamily, productSubCategory, mainProduct);

            List<mfg_Service_Term__c> newServiceTerms = buildServiceTerms(newProducts,productFamily,productSubCategory, mainProduct);

            if (!newServiceTerms.isEmpty()) {
                insert newServiceTerms;
                MFG_ServiceTermRulesetFramework.createStandardRules(newServiceTerms);
            }

            List<mfg_Product_Service_Term__c> newProductMappings = buildProductServiceTerms(newProducts,productFamily,productSubCategory,mainProduct);

            if (!newProductMappings.isEmpty()) {
                insert newProductMappings;
            }
            
        } catch (Exception ex) {
            System.debug('Service Term Error: ' + ex.getMessage());
        }
    }

    private static void existingServiceTerms(Map<String, mfg_Service_Term__c> productFamily,Map<String, mfg_Service_Term__c> productSubCategory,Map<String, mfg_Service_Term__c> mainProduct) {
        for (mfg_Service_Term__c term : [SELECT Id, Name, mfg_Service_Level__c, mfg_Service_Scope_Value__c  FROM mfg_Service_Term__c]) {
            if (term.mfg_Service_Level__c == 'Family') {
                productFamily.put(term.mfg_Service_Scope_Value__c, term);
            } else if (term.mfg_Service_Level__c == 'Subcategory') {
                productSubCategory.put(term.mfg_Service_Scope_Value__c, term);
            } else if (term.mfg_Service_Level__c == 'Product') {
                mainProduct.put(term.mfg_Service_Scope_Value__c, term);
            }
        }
    }

    private static List<mfg_Service_Term__c> buildServiceTerms(List<Product2> newProducts,Map<String, mfg_Service_Term__c> productFamily,Map<String, mfg_Service_Term__c> productSubCategory,Map<String, mfg_Service_Term__c> mainProduct) {
        List<mfg_Service_Term__c> newTerms = new List<mfg_Service_Term__c>();

        for (Product2 product : newProducts) {
            
            if (product.Family != null && !productFamily.containsKey(product.Family)) {
                mfg_Service_Term__c term = new mfg_Service_Term__c(
                    Name                    = product.Family + ' Service Term',
                    mfg_Service_Level__c    = 'Family',
                    mfg_Service_Scope_Value__c = product.Family,
                    mfg_Active__c           = true,
                    mfg_Activation_Date__c  = Date.today(),
                    mfg_Parts_Coverage__c   = 80,
                    mfg_Labor_Coverage__c   = 15,
                    mfg_Expense_Coverage__c = 5,
                    mfg_Service_Unit__c     = 'Months',
                    mfg_Service_Duration__c = 36
                );
                newTerms.add(term);
                productFamily.put(product.Family, term);
            }

            if (product.mfg_Product_Subcategory__c != null && !productSubCategory.containsKey(product.mfg_Product_Subcategory__c)) {

                mfg_Service_Term__c term = new mfg_Service_Term__c(
                    Name                    = product.mfg_Product_Subcategory__c + ' Service Term',
                    mfg_Service_Level__c    = 'Subcategory',
                    mfg_Service_Scope_Value__c = product.mfg_Product_Subcategory__c,
                    mfg_Active__c           = true,
                    mfg_Activation_Date__c  = Date.today(),
                    mfg_Parts_Coverage__c   = 75,
                    mfg_Labor_Coverage__c   = 20,
                    mfg_Expense_Coverage__c = 5,
                    mfg_Service_Unit__c     = 'Months',
                    mfg_Service_Duration__c = 24
                );
                newTerms.add(term);
                productSubCategory.put(product.mfg_Product_Subcategory__c, term);
            }

            if (!mainProduct.containsKey(product.Name)) {
                mfg_Service_Term__c term = new mfg_Service_Term__c(
                    Name                    = product.Name + ' Service Term',
                    mfg_Service_Level__c    = 'Product',
                    mfg_Service_Scope_Value__c = product.Name,
                    mfg_Active__c           = true,
                    mfg_Activation_Date__c  = Date.today(),
                    mfg_Parts_Coverage__c   = 70,
                    mfg_Labor_Coverage__c   = 25,
                    mfg_Expense_Coverage__c = 5,
                    mfg_Service_Unit__c     = 'Months',
                    mfg_Service_Duration__c = 12
                );
                newTerms.add(term);
                mainProduct.put(product.Name, term);
            }
        }
        return newTerms;
    }

    private static List<mfg_Product_Service_Term__c> buildProductServiceTerms(List<Product2> newProducts,Map<String, mfg_Service_Term__c> productFamily,Map<String, mfg_Service_Term__c> productSubCategory,Map<String, mfg_Service_Term__c> mainProduct) {
        List<mfg_Product_Service_Term__c> records = new List<mfg_Product_Service_Term__c>();

        for (Product2 product : newProducts) {

            if (product.Family != null && productFamily.containsKey(product.Family)) {
                records.add(new mfg_Product_Service_Term__c(
                    mfg_Covered_Product__c = product.Id,
                    mfg_Service_Term__c    = productFamily.get(product.Family).Id,
                    mfg_Service_Scope_Value__c = product.Family,
                    mfg_Service_Level__c ='Family'
                ));
            }

            if (product.mfg_Product_Subcategory__c != null && productSubCategory.containsKey(product.mfg_Product_Subcategory__c)) {

                records.add(new mfg_Product_Service_Term__c(
                    mfg_Covered_Product__c = product.Id,
                    mfg_Service_Term__c    = productSubCategory.get(product.mfg_Product_Subcategory__c).Id,
                    mfg_Service_Scope_Value__c = product.mfg_Product_Subcategory__c,
                    mfg_Service_Level__c ='Subcategory'
                ));
            }

            if (mainProduct.containsKey(product.Name)) {
                records.add(new mfg_Product_Service_Term__c(
                    mfg_Covered_Product__c = product.Id,
                    mfg_Service_Term__c    = mainProduct.get(product.Name).Id,
                    mfg_Service_Scope_Value__c = product.Name,
                    mfg_Service_Level__c ='Product'
                ));
            }
        }
        return records;
    }
}