MFG Ready Version/force-app/main/default/objects/mfg_Defect_Code__c/mfg_Defect_Code__c.object-meta.xml
<CustomObject>
    <label>Defect Code</label>
    <nameField>
        <label>Defect Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Defect Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MFG Ready Version/force-app/main/default/objects/mfg_Defect_Code__c/fields/mfg_Applicable_Families__c.field-meta.xml
<CustomField>
    <fullName>mfg_Applicable_Families__c</fullName>
    <label>Applicable Families</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>mfg_Product_Family</valueSetName>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Defect_Code__c/fields/mfg_Applicable_Products__c.field-meta.xml
<CustomField>
    <fullName>mfg_Applicable_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicable Products</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Defect Codes</relationshipLabel>
    <relationshipName>Defect_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Defect_Code__c/fields/mfg_Applicable_Subcategories__c.field-meta.xml
<CustomField>
    <fullName>mfg_Applicable_Subcategories__c</fullName>
    <label>Applicable Subcategories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>mfg_Product_Subcategory</valueSetName>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Defect_Code__c/fields/mfg_Defect_Applicability__c.field-meta.xml
<CustomField>
    <fullName>mfg_Defect_Applicability__c</fullName>
    <label>Defect Applicability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Include</fullName>
            </value>
            <value>
                <fullName>Exclude</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Defect_Code__c/fields/mfg_Defect_Level__c.field-meta.xml
<CustomField>
    <fullName>mfg_Defect_Level__c</fullName>
    <label>Defect Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Subcategory</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/mfg_Service_Term__c.object-meta.xml
<CustomObject>
    <label>Service Term</label>
    <nameField>
        <label>Service Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Active__c.field-meta.xml
<CustomField>
    <fullName>mfg_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Covered_Product__c.field-meta.xml
<CustomField>
    <fullName>mfg_Covered_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Covered Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Terms</relationshipLabel>
    <relationshipName>Service_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Service_Level__c.field-meta.xml
<CustomField>
    <fullName>mfg_Service_Level__c</fullName>
    <label>Service Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Subcategory</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term__c/fields/mfg_Service_Scope_Value__c.field-meta.xml
<CustomField>
    <fullName>mfg_Service_Scope_Value__c</fullName>
    <label>Service Scope Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term_RuleSet__c/mfg_Service_Term_RuleSet__c.object-meta.xml
<CustomObject>
    <label>Service Term RuleSet</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Service Term RuleSet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Term RuleSets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term_RuleSet__c/fields/mfg_Coverage_Action__c.field-meta.xml
<CustomField>
    <fullName>mfg_Coverage_Action__c</fullName>
    <label>Coverage Action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Include</fullName>
            </value>
            <value>
                <fullName>Exclude</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term_RuleSet__c/fields/mfg_Defect_Code__c.field-meta.xml
<CustomField>
    <fullName>mfg_Defect_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defect Code</label>
    <referenceTo>mfg_Defect_Code__c</referenceTo>
    <relationshipLabel>Service Term RuleSets</relationshipLabel>
    <relationshipName>Service_Term_RuleSets</relationshipName>
    <type>Lookup</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term_RuleSet__c/fields/mfg_Service_Term__c.field-meta.xml
<CustomField>
    <fullName>mfg_Service_Term__c</fullName>
    <label>Service Term</label>
    <referenceTo>mfg_Service_Term__c</referenceTo>
    <relationshipLabel>Service Term RuleSets</relationshipLabel>
    <relationshipName>Service_Term_RuleSets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Service_Term_RuleSet__c/fields/mfg_Standard__c.field-meta.xml
<CustomField>
    <fullName>mfg_Standard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Standard</label>
    <type>Checkbox</type>
</CustomField>

MFG Ready Version/force-app/main/default/globalValueSets/mfg_Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Generic</fullName>
        <default>true</default>
        <label>Generic</label>
    </customValue>
    <customValue>
        <fullName>Commercial Vehicles</fullName>
    </customValue>
    <customValue>
        <fullName>Compact Sedans</fullName>
    </customValue>
    <customValue>
        <fullName>Electric Vehicles</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchbacks</fullName>
    </customValue>
    <customValue>
        <fullName>SUVs And Crossovers</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

MFG Ready Version/force-app/main/default/globalValueSets/mfg_Product_Subcategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Anti-Diabetics</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Fungal</fullName>
    </customValue>
    <customValue>
        <fullName>Anti-Infective</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>Hematology</fullName>
    </customValue>
    <customValue>
        <fullName>Immunosuppressants</fullName>
    </customValue>
    <customValue>
        <fullName>Multiple Sclerosis</fullName>
    </customValue>
    <customValue>
        <fullName>Neurology</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology</fullName>
    </customValue>
    <customValue>
        <fullName>Battery And Power Unit</fullName>
    </customValue>
    <customValue>
        <fullName>Body And Trim</fullName>
    </customValue>
    <customValue>
        <fullName>Braking System</fullName>
    </customValue>
    <customValue>
        <fullName>Cab And Frame</fullName>
    </customValue>
    <customValue>
        <fullName>Chassis And Suspension</fullName>
    </customValue>
    <customValue>
        <fullName>Drivetrain</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical And Lighting</fullName>
    </customValue>
    <customValue>
        <fullName>Engine Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Exterior Components</fullName>
    </customValue>
    <customValue>
        <fullName>Fuel And Exhaust</fullName>
    </customValue>
    <customValue>
        <fullName>Infotainment</fullName>
    </customValue>
    <customValue>
        <fullName>Interior And Infotainment</fullName>
    </customValue>
    <customValue>
        <fullName>Interior Components</fullName>
    </customValue>
    <customValue>
        <fullName>Lightweight Body</fullName>
    </customValue>
    <customValue>
        <fullName>Motor And Controller</fullName>
    </customValue>
    <customValue>
        <fullName>Powertrain</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Components</fullName>
    </customValue>
    <customValue>
        <fullName>Thermal And Cooling</fullName>
    </customValue>
    <masterLabel>Product Subcategory</masterLabel>
</GlobalValueSet>

MFG Ready Version/force-app/main/default/classes/MFG_ServiceTermRulesetFramework.cls
public without sharing class MFG_ServiceTermRulesetFramework {
    
    public static void createStandardRules(List<mfg_Service_Term__c> serviceTerms) {
        
        if (serviceTerms == null || serviceTerms.isEmpty()) return;
        
        List<mfg_Defect_Code__c> defectCodes = [
            SELECT Id,mfg_Applicable_Products__c,mfg_Defect_Applicability__c FROM mfg_Defect_Code__c
            WHERE mfg_Active__c = true
        ];
        
        List<mfg_Service_Term_RuleSet__c> rulesets =new List<mfg_Service_Term_RuleSet__c>();
        
        for (mfg_Service_Term__c term : serviceTerms) {
            
            for (mfg_Defect_Code__c defect : defectCodes) {                
                
                if (!isScopeMatch(defect, term)) {
                    continue;
                }
                
                rulesets.add(new mfg_Service_Term_RuleSet__c(
                    mfg_Service_Term__c = term.Id,
                    mfg_Defect_Code__c  = defect.Id,
                    mfg_Standard__c     = true,
                    mfg_Coverage_Action__c =defect.mfg_Defect_Applicability__c
                ));
            }
        }
        
        if (!rulesets.isEmpty()) {
            System.debug('before insert rulesets =' +rulesets);
            insert rulesets;
             System.debug('after insert rulesets =' +rulesets);
        }
    }
    
    
    private static Boolean isScopeMatch( mfg_Defect_Code__c defect, mfg_Service_Term__c term) {
      
      
            return emptyOrContains( defect.mfg_Applicable_Products__c, term.mfg_Covered_Product__r.Name);
        

    }
    
    
    private static Boolean emptyOrContains(String values, String target) {
        if (String.isBlank(values)) return true;
        
        for (String v : values.split(';')) {
            if (v.trim().equalsIgnoreCase(target)) {
                return true;
            }
        }
        return false;
    }
}




















/**public without sharing class MFG_ServiceTermRulesetFramework {
    
    public static void createStandardRules(List<mfg_Service_Term__c> serviceTerms) {
        
        if (serviceTerms == null || serviceTerms.isEmpty()) return;
        
        List<mfg_Defect_Code__c> defectCodes = [
            SELECT Id, mfg_Defect_Level__c,mfg_Applicable_Families__c,mfg_Applicable_Subcategories__c,mfg_Applicable_Products__c FROM mfg_Defect_Code__c
            WHERE mfg_Active__c = true
        ];
        
        List<mfg_Service_Term_RuleSet__c> rulesets =new List<mfg_Service_Term_RuleSet__c>();
        
        for (mfg_Service_Term__c term : serviceTerms) {
            
            for (mfg_Defect_Code__c defect : defectCodes) {
                
                if (!multiSelectContains(defect.mfg_Defect_Level__c, term.mfg_Service_Level__c)) {
                    continue;
                }
                
                if (!isScopeMatch(defect, term)) {
                    continue;
                }
                
                rulesets.add(new mfg_Service_Term_RuleSet__c(
                    mfg_Service_Term__c = term.Id,
                    mfg_Defect_Code__c  = defect.Id,
                    mfg_Standard__c     = true
                ));
            }
        }
        
        if (!rulesets.isEmpty()) {
            insert rulesets;
        }
    }
    
    
    private static Boolean isScopeMatch( mfg_Defect_Code__c defect, mfg_Service_Term__c term) {
        
        if (term.mfg_Service_Level__c == 'Family') {
            return emptyOrContains( defect.mfg_Applicable_Families__c, term.mfg_Service_Scope_Value__c);
        }
        
        if (term.mfg_Service_Level__c == 'Subcategory') {
            return emptyOrContains(defect.mfg_Applicable_Subcategories__c,term.mfg_Service_Scope_Value__c );
        }
        
        if (term.mfg_Service_Level__c == 'Product') {
            return emptyOrContains( defect.mfg_Applicable_Products__c, term.mfg_Service_Scope_Value__c);
        }
        
        return false;
    }
    
    private static Boolean multiSelectContains(String values, String target) {
        if (String.isBlank(values) || String.isBlank(target)) return false;
        
        for (String v : values.split(';')) {
            if (v.trim().equalsIgnoreCase(target)) {
                return true;
            }
        }
        return false;
    }
    
    private static Boolean emptyOrContains(String values, String target) {
        if (String.isBlank(values)) return true;
        
        for (String v : values.split(';')) {
            if (v.trim().equalsIgnoreCase(target)) {
                return true;
            }
        }
        return false;
    }
}**/