MFG Ready Version/force-app/main/default/objects/Asset/fields/mfg_Asset_Number__c.field-meta.xml
<CustomField>
    <fullName>mfg_Asset_Number__c</fullName>
    <displayFormat>A-{YYYY}{MM}{DD}-{0000000000}</displayFormat>
    <label>Asset Number</label>
    <type>AutoNumber</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/Asset/fields/mfg_Production_Batch_Unit__c.field-meta.xml
<CustomField>
    <fullName>mfg_Production_Batch_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Batch Unit</label>
    <referenceTo>mfg_Production_Batch_Unit__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

MFG Ready Version/force-app/main/default/objects/mfg_Production_Batch_Unit__c/mfg_Production_Batch_Unit__c.object-meta.xml
<CustomObject>
    <label>Production Batch Unit</label>
    <nameField>
        <displayFormat>PBU-{YYYY}{MM}{DD}-{0000000000}</displayFormat>
        <label>Production Batch Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Batch Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MFG Ready Version/force-app/main/default/objects/mfg_Production_Batch_Unit__c/fields/mfg_Asset_Number__c.field-meta.xml
<CustomField>
    <fullName>mfg_Asset_Number__c</fullName>
    <formula>mfg_Asset__r.mfg_Asset_Number__c</formula>
    <inlineHelpText>Asset Number is useful to track the product after sales.</inlineHelpText>
    <label>Asset Number</label>
    <type>Text</type>
</CustomField>

MFG Ready Version/force-app/main/default/classes/MFG_AssetDetails.cls
public with sharing class MFG_AssetDetails {
@AuraEnabled(cacheable = true)
  public static List<Asset> assetList(){
    try {
      return [SELECT Id,Name,Account.Name,Product2.Name,AccountId,Product2Id,Status,mfg_Asset_Number__c,ContactId,ProductCode,mfg_Production_Batch_Unit__c,Quantity,InstallDate,PurchaseDate,UsageEndDate FROM Asset ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}