SIS/force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Parent_Email_Address__c</fullName>
    <label>Parent Email Address</label>
    <type>Email</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>Parent_NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Relationship_Father_Mother__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Father_Mother__c</fullName>
    <label>Parent Relationship (Father/Mother)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunty</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Accounts</relationshipLabel>
    <relationshipName>PrimaryAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/recordTypes/Campus_ID.recordType-meta.xml
<RecordType>
    <fullName>Campus_ID</fullName>
    <active>true</active>
    <label>Campus ID</label>
</RecordType>

SIS/force-app/main/default/objects/Contact/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Intake_Master__c/Intake_Master__c.object-meta.xml
<CustomObject>
    <label>Intake Master</label>
    <nameField>
        <displayFormat>IM-{00000}</displayFormat>
        <label>Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intake Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Intake_Master__c/fields/Programme_Master__c.field-meta.xml
<CustomField>
    <fullName>Programme_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme Master</label>
    <referenceTo>Programme_Master__c</referenceTo>
    <relationshipLabel>Intake Masters</relationshipLabel>
    <relationshipName>Intake_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Mobile_Phone_1__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone_1__c</fullName>
    <label>Mobile Phone 1</label>
    <type>Phone</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Leads</relationshipLabel>
    <relationshipName>Child_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Parent_Lead__c.field-meta.xml
<CustomField>
    <fullName>Parent_Lead__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Lead</label>
    <referenceTo>Parent_Lead__c</referenceTo>
    <relationshipLabel>Child Leads</relationshipLabel>
    <relationshipName>Child_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/Parent_Lead__c.object-meta.xml
<CustomObject>
    <label>Parent Lead</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parent Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Campus__c.field-meta.xml
<CustomField>
    <fullName>Campus__c</fullName>
    <label>Campus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SISKL</fullName>
            </value>
            <value>
                <fullName>SISJB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Mobile_Number_1__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_1__c</fullName>
    <label>Mobile Number 1</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/Programme_Master__c.object-meta.xml
<CustomObject>
    <label>Programme Master</label>
    <nameField>
        <label>Programme Master  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Campus_Code__c.field-meta.xml
<CustomField>
    <fullName>Campus_Code__c</fullName>
    <label>Campus Code</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Campus_Location__c.field-meta.xml
<CustomField>
    <fullName>Campus_Location__c</fullName>
    <label>Campus Location</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Campus_Name__c.field-meta.xml
<CustomField>
    <fullName>Campus_Name__c</fullName>
    <label>Campus Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Campus_SFID__c.field-meta.xml
<CustomField>
    <fullName>Campus_SFID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campus SFID</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please Select a Valid Campus</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Campus_ID</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programme Masters</relationshipLabel>
    <relationshipName>Programme_Masters</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Is_Offer__c.field-meta.xml
<CustomField>
    <fullName>Is_Offer__c</fullName>
    <label>Is Offer</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Level_of_Education__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Education__c</fullName>
    <label>Level of Education</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Programme_Code__c.field-meta.xml
<CustomField>
    <fullName>Programme_Code__c</fullName>
    <label>Programme Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Programme_Duration__c.field-meta.xml
<CustomField>
    <fullName>Programme_Duration__c</fullName>
    <label>Programme Duration</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/fields/School_Code__c.field-meta.xml
<CustomField>
    <fullName>School_Code__c</fullName>
    <label>School Code</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Student__c/fields/Campus_SFID__c.field-meta.xml
<CustomField>
    <fullName>Campus_SFID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campus SFID</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please Select a Valid Campus.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Campus_ID</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>NRIC/Passport No.</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MELBOURNE</fullName>
    </customValue>
    <customValue>
        <fullName>SYDNEY</fullName>
    </customValue>
    <customValue>
        <fullName>WESTERN AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>BARISAL</fullName>
    </customValue>
    <customValue>
        <fullName>CHITTAGONG</fullName>
    </customValue>
    <customValue>
        <fullName>DHAKA</fullName>
    </customValue>
    <customValue>
        <fullName>BUBANZA</fullName>
    </customValue>
    <customValue>
        <fullName>BUJUMBURA</fullName>
    </customValue>
    <customValue>
        <fullName>BURURI</fullName>
    </customValue>
    <customValue>
        <fullName>CANKUZO</fullName>
    </customValue>
    <customValue>
        <fullName>CIBITOKE</fullName>
    </customValue>
    <customValue>
        <fullName>GITEGA</fullName>
    </customValue>
    <customValue>
        <fullName>KARUZI</fullName>
    </customValue>
    <customValue>
        <fullName>KAYANZA</fullName>
    </customValue>
    <customValue>
        <fullName>KIRUNDO</fullName>
    </customValue>
    <customValue>
        <fullName>MAKAMBA</fullName>
    </customValue>
    <customValue>
        <fullName>MURAMVYA</fullName>
    </customValue>
    <customValue>
        <fullName>MUYINGA</fullName>
    </customValue>
    <customValue>
        <fullName>MWARO</fullName>
    </customValue>
    <customValue>
        <fullName>NGOZI</fullName>
    </customValue>
    <customValue>
        <fullName>RUTANA</fullName>
    </customValue>
    <customValue>
        <fullName>RUYIGI</fullName>
    </customValue>
    <customValue>
        <fullName>ANHUI</fullName>
    </customValue>
    <customValue>
        <fullName>BEIJING</fullName>
    </customValue>
    <customValue>
        <fullName>CHONGQING</fullName>
    </customValue>
    <customValue>
        <fullName>FUJIAN</fullName>
    </customValue>
    <customValue>
        <fullName>GANSU</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGDONG</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGXI</fullName>
    </customValue>
    <customValue>
        <fullName>GUIZHOU</fullName>
    </customValue>
    <customValue>
        <fullName>MALE</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

SIS/force-app/main/default/classes/LeadManagementAPITest.cls
@IsTest
private class LeadManagementAPITest {
    
    @testSetup
    public static void setUpData(){
        // Create Campus
        List<RecordType> rt = new List<RecordType>();
        rt = [Select Id From RecordType Where DeveloperName = 'Campus_ID' LIMIT 1];
        
        Account account = new Account();
        account.RecordTypeId = rt[0].Id;
        account.Name = 'SISJ';
        insert account;
        
        //Create Parent Lead
        Parent_Lead__c pl = new Parent_Lead__c();
        pl.Name = 'testParentLead';
        pl.Campus__c = 'SIS';
        pl.Email__c = 'parentlead@gmail.com';
        pl.Mobile_Number_1__c = '1234567890';
        insert pl;
        
        //Create Parent Lead for update
        Parent_Lead__c plforUpdate = new Parent_Lead__c();
        plforUpdate.Name = 'testParentLead';
        plforUpdate.Campus__c = 'SIS';
        plforUpdate.Email__c = 'sam07200@gmail.com';
        plforUpdate.Mobile_Number_1__c = '9878093226';
        insert plforUpdate;
        
        //Create Child Lead
        Lead cl = new Lead();
        cl.LastName = 'testchildLead';
        cl.Date_of_Birth__c = date.today()-200;
        cl.Status = 'New';
        cl.Parent_Lead__c = pl.Id;
        insert cl;
        
        //Create Child Lead for update
        Lead clforUpdate = new Lead();
        clforUpdate.LastName = 'Anjali';
        clforUpdate.Date_of_Birth__c = Date.newInstance(2005,04,21);
        clforUpdate.Status = 'New';
        clforUpdate.Email='Anjali07@gmail.com';
        clforUpdate.Parent_Lead__c = plforUpdate.Id;
        clforUpdate.Mobile_Phone_1__c = '9943678161';
        insert clforUpdate;
        
        //Create Account
        Account acc = new Account();
        acc.Name = 'TestName';
        acc.Parent_NRIC_Passport_No__c = '112233445566';
        acc.Parent_Relationship_Father_Mother__c='Mother';
        acc.Parent_Email_Address__c='xyz@gmail.com';
        acc.Phone='60456183447';
        acc.Street__c='xyz';
        acc.City__c='xyz';
        acc.State__c='SYDNEY';
        acc.Country__c='MY';
        acc.Postcode__c='756532';
        insert acc;
        
        //Create Account for update
        Account accupdate = new Account();
        accupdate.Name = 'TestName';
        accupdate.Parent_Email_Address__c='arun1@gmail.com';
        accupdate.Parent_NRIC_Passport_No__c = '637977928989';
        accupdate.Parent_Relationship_Father_Mother__c = 'Mother';
        accupdate.Phone='61456183447';
        accupdate.Street__c='xyz';
        accupdate.City__c='xyz';
        accupdate.State__c='SYDNEY';
        accupdate.Country__c='MY';
        accupdate.Postcode__c='756532';
        insert accupdate;
        
        //Create Contact
        Contact con = new Contact();
        con.Primary_Account__c = acc.Id;
        con.LastName = 'TestConName';
        con.Primary_Contact__c = true;
        con.Email='abc@gmail.com';
        con.MobilePhone='61456183447';
        con.NRIC_Passport_No__c='551133667711';
        insert con;
        
        //Create Contact for update
        Contact conUpdate = new Contact();
        conUpdate.Primary_Account__c = accupdate.Id;
        conUpdate.LastName = 'TestConName';
        conUpdate.NRIC_Passport_No__c = '637977928989';
        conUpdate.Email = 'arun107@gmail.com';
        conUpdate.MobilePhone='8899066550';
        conUpdate.Primary_Contact__c = true;
        insert conUpdate;
        
        //Create Student
        Student__c stud = new Student__c();
        stud.Name = 'TestStudName';
        stud.Parent_Account__c = acc.Id;
        stud.NRIC_Passport_No__c = '994411778855';
        stud.Date_of_Birth__c = Date.today() - 100;
        insert stud;
        
        //Programme Master
        Programme_Master__c pMaster = new Programme_Master__c();
        pMaster.Name = 'TestPMaster';
        pMaster.Programme_Code__c = '123';
        pMaster.Programme_Duration__c = 12;
        pMaster.Level_of_Education__c = 'Primary';
        pMaster.Is_Offer__c = 'y';
        pMaster.Campus_SFID__c = account.Id;
        pMaster.Campus_Code__c = 'SIS123';
        pMaster.Campus_Name__c = 'SIS';
        pMaster.Campus_Location__c = 'malaysia';
        pMaster.School_Code__c = 'SIS789';
        insert pMaster;
        
        //Intake Master
        Intake_Master__c iMaster = new Intake_Master__c();
        iMaster.Intake_Number__c = '789456123';
        iMaster.Study_Mode__c = 'Online';
        iMaster.Course_Detail_Intake_ID__c = 123987;
        iMaster.Application_Allowed__c = 'YES';
        iMaster.Programme_Master__c = pMaster.Id;
        insert iMaster;
    }
    
    @IsTest
    static void testCreateLead() {
        String pmName = [SELECT Name FROM Programme_Master__c WHERE Name = 'TestPMaster' LIMIT 1].Name;
        String imName = [SELECT Name FROM Intake_Master__c WHERE Intake_Number__c ='789456123' LIMIT 1].Name;
        
        Map<String, Object> parentMap = new Map<String, Object>();
        parentMap.put('parentCampus', 'MGR University');
        parentMap.put('parentRelationship', 'Mother');
        parentMap.put('parentLeadName', 'Samantha');
        parentMap.put('parentEmail', 'samantha@gmail.com');
        parentMap.put('parentDateofBirth', '2001-02-01');
        parentMap.put('parentMobileNumber1', '9189134567');
        parentMap.put('parentMobileNumber2', '9783491465');
        parentMap.put('parentMobileNumber3', '6589044667');
        parentMap.put('parentPreferredPhoneNumber', 'Mobile Phone 1');
        parentMap.put('parentPassportIC', '551133661111');
        //parentMap.put('parentCitizenship', 'Malaysian');
        parentMap.put('parentGender', 'FEMALE');
        parentMap.put('parentCity', 'Chennai');
        parentMap.put('parentStateProvince', 'SYDNEY');
        parentMap.put('parentCompany', 'MGR Company');
        parentMap.put('parentPhoneCompany', '1234222343');
        parentMap.put('parentStreet', 'Karaikal street');
        parentMap.put('parentPostcode', '632607');
        parentMap.put('parentCountry', 'MY');
        parentMap.put('parentPassportExpiry', '2028-02-22');
        parentMap.put('parentNationality','MY');
        
        Map<String, Object> childMap = new Map<String, Object>();
        childMap.put('childName', 'Vetri');
        childMap.put('childDateofBirth', '2005-04-21');
        childMap.put('childNationality', 'AD');
        childMap.put('childCitizenship', 'Malaysian');
        childMap.put('childPassportIC', '345365471234');
        childMap.put('childPassportExpiry', '2089-03-21');
        childMap.put('childEmail', 'Vetri@gmail.com');
        childMap.put('childMobilePhone1', '7128987654');
        childMap.put('childMobilePhone2', '7234563234');
        childMap.put('childMobilePhone3', '8234567895');
        childMap.put('childPreferredPhone', 'Mobile Phone 1');
        childMap.put('childProgramme', pmName);
        childMap.put('childIntake', imName);
        childMap.put('childVisa', 'DEPENDENT (EXPATRIATE/EMPLOYMENT)');
        childMap.put('childGender', 'MALE');
        childMap.put('childAccommodation', 'true');
        childMap.put('childBursary', 'true');
        childMap.put('childScholarship', 'true');
        childMap.put('childLeadStatus', 'NEW');
        childMap.put('childLostreason', '');
        childMap.put('childLeadSource', 'PHONE INQUIRY');
        childMap.put('childLeadRating', 'HOT');
        childMap.put('childPassportIssuefrom', 'MY');
        childMap.put('childCurrentSchool', 'SSC Mandhri Higher Secondary School');
        childMap.put('childCompletedGrade', 'Grade 3 / Year 3');
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('parentLead', parentMap);
        requestBodyMap.put('childLead', childMap);
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        LeadManagementAPI.createLead();
        Test.stopTest();
    }
    
    @IsTest
    static void testCreateLeadForUpdate(){
        String pmName = [SELECT Name FROM Programme_Master__c WHERE Name = 'TestPMaster' LIMIT 1].Name;
        String imName = [SELECT Name FROM Intake_Master__c WHERE Intake_Number__c ='789456123' LIMIT 1].Name;
        Map<String, Object> parentMap = new Map<String, Object>();
        parentMap.put('parentCampus', 'MGR University');
        parentMap.put('parentRelationship', 'Mother');
        parentMap.put('parentLeadName', 'Samantha');
        parentMap.put('parentEmail', 'sam07200@gmail.com');
        parentMap.put('parentDateofBirth', '2001-02-01');
        parentMap.put('parentMobileNumber1', '9878093226');
        parentMap.put('parentMobileNumber2', '9783491465');
        parentMap.put('parentMobileNumber3', '6589044667');
        parentMap.put('parentPreferredPhoneNumber', 'Mobile Phone 1');
        parentMap.put('parentPassportIC', '551133667755');
        parentMap.put('parentCitizenship', 'Malaysian');
        parentMap.put('parentGender', 'FEMALE');
        parentMap.put('parentCity', 'Chennai');
        parentMap.put('parentStateProvince', 'SYDNEY');
        parentMap.put('parentCompany', 'MGR Company');
        parentMap.put('parentPhoneCompany', '1234222343');
        parentMap.put('parentStreet', 'Karaikal street');
        parentMap.put('parentPostcode', '632607');
        parentMap.put('parentCountry', 'MY');
        parentMap.put('parentPassportExpiry', '2028-02-22');
        
        Map<String, Object> childMap = new Map<String, Object>();
        childMap.put('childName', 'Anjali');
        childMap.put('childDateofBirth', '2005-04-21');
        childMap.put('childNationality', 'AD');
        childMap.put('childCitizenship', 'Malaysian');
        childMap.put('childPassportIC', '794911166612');
        childMap.put('childPassportExpiry', '2089-03-21');
        childMap.put('childEmail', 'Anjali07@gmail.com');
        childMap.put('childMobilePhone1', '9943678161');
        childMap.put('childMobilePhone2', '7234563234');
        childMap.put('childMobilePhone3', '8234567895');
        childMap.put('childPreferredPhone', 'Mobile Phone 1');
        childMap.put('childProgramme', pmName);
        childMap.put('childIntake', imName);
        childMap.put('childVisa', 'DEPENDENT (EXPATRIATE/EMPLOYMENT)');
        childMap.put('childGender', 'FEMALE');
        childMap.put('childAccommodation', 'true');
        childMap.put('childBursary', 'true');
        childMap.put('childScholarship', 'true');
        childMap.put('childLeadStatus', 'LOST');
        childMap.put('childLostreason', 'UNWILLING TO DISCLOSE');
        childMap.put('childLeadSource', 'PHONE INQUIRY');
        childMap.put('childLeadRating', 'HOT');
        childMap.put('childPassportIssuefrom', 'MY');
        childMap.put('childCurrentSchool', 'SSC Mandhri Higher Secondary School');
        childMap.put('childCompletedGrade', 'Grade 3 / Year 3');
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('parentLead', parentMap);
        requestBodyMap.put('childLead', childMap);
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        LeadManagementAPI.createLead();
        Test.stopTest();
    }
    
    @IsTest
    static void updateAccountAndStudent(){
        String pmName = [SELECT Name FROM Programme_Master__c WHERE Name = 'TestPMaster' LIMIT 1].Name;
        String imName = [SELECT Name FROM Intake_Master__c WHERE Intake_Number__c ='789456123' LIMIT 1].Name;
        Map<String, Object> parentMap = new Map<String, Object>();
        parentMap.put('parentCampus', 'MGR University');
        parentMap.put('parentRelationship', 'Mother');
        parentMap.put('parentLeadName', 'Arun');
        parentMap.put('parentEmail', 'arun107@gmail.com');
        parentMap.put('parentDateofBirth', '2002-02-01');
        parentMap.put('parentMobileNumber1', '8899066550');
        parentMap.put('parentMobileNumber2', '9783491465');
        parentMap.put('parentMobileNumber3', '6589044667');
        parentMap.put('parentPreferredPhoneNumber', 'Mobile Phone 1');
        parentMap.put('parentPassportIC', '637977928989');
        parentMap.put('parentCitizenship', 'Malaysian');
        parentMap.put('parentGender', 'FEMALE');
        parentMap.put('parentCity', 'Chennai');
        parentMap.put('parentStateProvince', 'SYDNEY');
        parentMap.put('parentCompany', 'MGR Company');
        parentMap.put('parentPhoneCompany', '1234222343');
        parentMap.put('parentStreet', 'Karaikal street');
        parentMap.put('parentPostcode', '632607');
        parentMap.put('parentCountry', 'MY');
        parentMap.put('parentPassportExpiry', '2028-02-22');
        
        Map<String, Object> childMap = new Map<String, Object>();
        childMap.put('childName', 'Ranjith');
        childMap.put('childDateofBirth', '2009-04-21');
        childMap.put('childNationality', 'AD');
        childMap.put('childCitizenship', 'Malaysian');
        childMap.put('childPassportIC', '994411778855');
        childMap.put('childPassportExpiry', '2089-03-21');
        childMap.put('childEmail', 'ranjith@gmail.com');
        childMap.put('childMobilePhone1', '4876189753');
        childMap.put('childMobilePhone2', '7234563234');
        childMap.put('childMobilePhone3', '8234567895');
        childMap.put('childPreferredPhone', 'Mobile Phone 1');
        childMap.put('childProgramme', pmName);
        childMap.put('childIntake', imName);
        childMap.put('childVisa', 'DEPENDENT (EXPATRIATE/EMPLOYMENT)');
        childMap.put('childGender', 'Male');
        childMap.put('childAccommodation', 'true');
        childMap.put('childBursary', 'true');
        childMap.put('childScholarship', 'true');
        childMap.put('childLeadStatus', 'New');
        childMap.put('childLostreason', '');
        childMap.put('childLeadSource', 'Tawk-to-chat');
        childMap.put('childLeadRating', 'Hot');
        childMap.put('childPassportIssuefrom', 'MY');
        childMap.put('childCurrentSchool', 'SSC Mandhri Higher Secondary School');
        childMap.put('childCompletedGrade', 'Grade 3 / Year 3');
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('parentLead', parentMap);
        requestBodyMap.put('childLead', childMap);
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        LeadManagementAPI.createLead();
        Test.stopTest();
    }
    
    @IsTest
    static void missingField(){
        Map<String, Object> parentMap = new Map<String, Object>();
        parentMap.put('parentCampus', '');
        parentMap.put('parentRelationship', 'Mother');
        parentMap.put('parentLeadName', 'Arun');
        parentMap.put('parentEmail', '');
        parentMap.put('parentDateofBirth', '2002-02-01');
        parentMap.put('parentMobileNumber1', '');
        parentMap.put('parentMobileNumber2', '9783491465');
        parentMap.put('parentMobileNumber3', '6589044667');
        parentMap.put('parentPreferredPhoneNumber', 'Mobile Phone 1');
        parentMap.put('parentPassportIC', '');
        
        
        Map<String, Object> childMap = new Map<String, Object>();
        childMap.put('childName', '');
        childMap.put('childDateofBirth', '');
        childMap.put('childNationality', 'AD');
        childMap.put('childPassportIC', '');
        childMap.put('childEmail', '');
        childMap.put('childMobilePhone1', '');
        childMap.put('childPreferredPhone', 'Mobile Phone 1');
        childMap.put('childVisa', 'DEPENDENT (EXPATRIATE/EMPLOYMENT)');
        childMap.put('childGender', 'MALE');
        childMap.put('childLeadStatus', '');
        childMap.put('childLostreason', '');
        childMap.put('childLeadSource', 'Tawk-to-chat');
        childMap.put('childLeadRating', 'Hot');
        
        
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('parentLead', parentMap);
        requestBodyMap.put('childLead', childMap);
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        LeadManagementAPI.createLead();
        Test.stopTest();
    }
    @IsTest
    static void missinFieldChild(){
        Map<String, Object> parentMap = new Map<String, Object>();
        parentMap.put('parentCampus', 'SISKL');
        parentMap.put('parentRelationship', 'Mother');
        parentMap.put('parentLeadName', 'abc');
        parentMap.put('parentEmail', 'abc07@gmail.com');
        parentMap.put('parentMobileNumber1', '5346536643');
        
        
        
        Map<String, Object> childMap = new Map<String, Object>();
        childMap.put('childName', '');
        childMap.put('childDateofBirth', '');
        childMap.put('childMobilePhone1', '');
        childMap.put('childLeadStatus', '');
        
        
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('parentLead', parentMap);
        requestBodyMap.put('childLead', childMap);
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        LeadManagementAPI.createLead();
        Test.stopTest();
    }
    @IsTest
    static void coverMyException(){
        Map<String, Object> parentMap = new Map<String, Object>();
        parentMap.put('parentCampus', 'SISKL');
        parentMap.put('parentRelationship', 'Mother');
        parentMap.put('parentLeadName', 'abc');
        parentMap.put('parentEmail', 'abc07@gmail.com');
        parentMap.put('parentMobileNumber1', '5346536643');
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('parentLead', parentMap);
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        LeadManagementAPI.createLead();
        Test.stopTest();
    }
}