SIS/force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Emergency_Contact_home__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_home__c</fullName>
    <label>Emergency Contact home</label>
    <type>Phone</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Emergency_Contact_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Mobile__c</fullName>
    <label>Emergency Contact Mobile</label>
    <type>Phone</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Emergency_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Name__c</fullName>
    <label>Emergency Contact Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Emergency_Email__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Email__c</fullName>
    <label>Emergency Email</label>
    <type>Email</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Contact_Telephone__c.field-meta.xml
<CustomField>
    <fullName>Parent_Contact_Telephone__c</fullName>
    <label>Parent Contact Telephone</label>
    <type>Phone</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Parent_Email_Address__c</fullName>
    <label>Parent Email Address</label>
    <type>Email</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>Parent_NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Occupation__c.field-meta.xml
<CustomField>
    <fullName>Parent_Occupation__c</fullName>
    <label>Parent Occupation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Relationship_Father_Mother__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Father_Mother__c</fullName>
    <label>Parent Relationship (Father/Mother)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunty</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/Programme_Application__c.object-meta.xml
<CustomObject>
    <label>Programme Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Programme Application No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programme Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Programme_Application__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Programme Applications</relationshipLabel>
    <relationshipName>Programme_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Student__c/fields/Campus_SFID__c.field-meta.xml
<CustomField>
    <fullName>Campus_SFID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campus SFID</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please Select a Valid Campus.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Campus_ID</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/City_m__c.field-meta.xml
<CustomField>
    <fullName>City_m__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/City_p__c.field-meta.xml
<CustomField>
    <fullName>City_p__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Contact_Telephone_No_m__c.field-meta.xml
<CustomField>
    <fullName>Contact_Telephone_No_m__c</fullName>
    <label>Contact Telephone No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Contact_Telephone_No_p__c.field-meta.xml
<CustomField>
    <fullName>Contact_Telephone_No_p__c</fullName>
    <label>Contact Telephone No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Country_m__c.field-meta.xml
<CustomField>
    <fullName>Country_m__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Country_p__c.field-meta.xml
<CustomField>
    <fullName>Country_p__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Emergency_Contact_home__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_home__c</fullName>
    <label>Emergency Contact home</label>
    <type>Phone</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Emergency_Contact_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Mobile__c</fullName>
    <label>Emergency Contact Mobile</label>
    <type>Phone</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Emergency_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Name__c</fullName>
    <label>Emergency Contact Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Emergency_Email__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Email__c</fullName>
    <label>Emergency Email</label>
    <type>Email</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Emergency_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Relationship__c</fullName>
    <label>Emergency Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunty</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorce</fullName>
            </value>
            <value>
                <fullName>Widow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Postcode_m__c.field-meta.xml
<CustomField>
    <fullName>Postcode_m__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Postcode_p__c.field-meta.xml
<CustomField>
    <fullName>Postcode_p__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Name__c</fullName>
    <label>Preferred Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Religion__c.field-meta.xml
<CustomField>
    <fullName>Religion__c</fullName>
    <label>Religion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUDDHIST</fullName>
            </value>
            <value>
                <fullName>CHRISTIAN</fullName>
            </value>
            <value>
                <fullName>HINDU</fullName>
            </value>
            <value>
                <fullName>MUSLIM</fullName>
            </value>
            <value>
                <fullName>SIKH</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/State_m__c.field-meta.xml
<CustomField>
    <fullName>State_m__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/State_p__c.field-meta.xml
<CustomField>
    <fullName>State_p__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Street_m__c.field-meta.xml
<CustomField>
    <fullName>Street_m__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Street_p__c.field-meta.xml
<CustomField>
    <fullName>Street_p__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Student_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Student_Mobile_No__c</fullName>
    <label>Student Mobile No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MELBOURNE</fullName>
    </customValue>
    <customValue>
        <fullName>SYDNEY</fullName>
    </customValue>
    <customValue>
        <fullName>WESTERN AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>BARISAL</fullName>
    </customValue>
    <customValue>
        <fullName>CHITTAGONG</fullName>
    </customValue>
    <customValue>
        <fullName>DHAKA</fullName>
    </customValue>
    <customValue>
        <fullName>BUBANZA</fullName>
    </customValue>
    <customValue>
        <fullName>BUJUMBURA</fullName>
    </customValue>
    <customValue>
        <fullName>BURURI</fullName>
    </customValue>
    <customValue>
        <fullName>CANKUZO</fullName>
    </customValue>
    <customValue>
        <fullName>CIBITOKE</fullName>
    </customValue>
    <customValue>
        <fullName>GITEGA</fullName>
    </customValue>
    <customValue>
        <fullName>KARUZI</fullName>
    </customValue>
    <customValue>
        <fullName>KAYANZA</fullName>
    </customValue>
    <customValue>
        <fullName>KIRUNDO</fullName>
    </customValue>
    <customValue>
        <fullName>MAKAMBA</fullName>
    </customValue>
    <customValue>
        <fullName>MURAMVYA</fullName>
    </customValue>
    <customValue>
        <fullName>MUYINGA</fullName>
    </customValue>
    <customValue>
        <fullName>MWARO</fullName>
    </customValue>
    <customValue>
        <fullName>NGOZI</fullName>
    </customValue>
    <customValue>
        <fullName>RUTANA</fullName>
    </customValue>
    <customValue>
        <fullName>RUYIGI</fullName>
    </customValue>
    <customValue>
        <fullName>ANHUI</fullName>
    </customValue>
    <customValue>
        <fullName>BEIJING</fullName>
    </customValue>
    <customValue>
        <fullName>CHONGQING</fullName>
    </customValue>
    <customValue>
        <fullName>FUJIAN</fullName>
    </customValue>
    <customValue>
        <fullName>GANSU</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGDONG</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGXI</fullName>
    </customValue>
    <customValue>
        <fullName>GUIZHOU</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

SIS/force-app/main/default/classes/StudentChangeHandler.cls
public class StudentChangeHandler {
    public static String clientID = System.Label.SIS_clientID;
    private static String orgId;
    
    private static String getOrgId() {
        if (orgId == null) {
            String fullOrgId = [SELECT Id FROM Organization LIMIT 1].Id;
            orgId=fullOrgId.substring(0, 15);
        }
        return orgId;
    }
    
    public static final Map<String, String> studentFieldMap = new Map<String, String>{
            'Marital_Status__c' => 'MARITAL_STATUS',
            'Religion__c' => 'RELIGION',
            'Street_m__c' => 'RESIDENTIAL_STREET',
            'Postcode_m__c' => 'RESIDENTIAL_POSTCODE',
            'City_m__c' => 'RESIDENTIAL_CITY',
            'State_m__c' => 'RESIDENTIAL_STATE',
            'Country_m__c' => 'RESIDENTIAL_COUNTRY',
            'Contact_Telephone_No_m__c' => 'RESIDENTIAL_TEL_NO',
            'Student_Mobile_No__c' => 'STUDENT_MOBILE_NO',
            'Email_Address__c' => 'E_MAIL',
            'City_p__c' => 'PERMANENT_CITY',
            'Street_p__c' => 'PERMANENT_STREET',
            'Postcode_p__c' => 'PERMANENT_POSTCODE',
            'State_p__c' => 'PERMANENT_STATE',
            'Country_p__c' => 'PERMANENT_COUNTRY',
            'Contact_Telephone_No_p__c' => 'PERMANENT_TEL_NO',
            'Preferred_Name__c' => 'PREFERRED_NAME',
            'Emergency_Contact_Name__c' => 'EMERGENCY_NAME',
            'Emergency_Relationship__c' => 'EMERGENCY_RELATIONSHIP',
            'Emergency_Contact_home__c' => 'EMERGENCY_CONTACT_HOME',
            'Emergency_Contact_Mobile__c' => 'EMERGENCY_CONTACT_MOBILE',
             'Emergency_Email__c' => 'EMERGENCY_EMAIL'   
            };
                
                
                public static final Map<String, String> parentFieldMap = new Map<String, String>{
                    'Name' => 'PARENTS_NAME',
                        'Parent_Relationship_Father_Mother__c' => 'PARENTS_RELATIONSHIP',
                        'Parent_Contact_Telephone__c' => 'PARENTS_RESIDENTIAL_TEL',
                        'Phone' => 'PARENT_MOBILE_NO',
                        'Parent_Email_Address__c' => 'PARENTS_EMAIL',
                        'Parent_NRIC_Passport_No__c' => 'PARENTS_IC_PASSPORT',
                        'Parent_Occupation__c' => 'PARENTS_OCCUPATION',
                        'Street__c' => 'PARENTS_RESIDENTIAL_STREET',
                        'Postcode__c' => 'PARENTS_RESIDENTIAL_POSTCODE',
                        'City__c' => 'PARENTS_RESIDENTIAL_CITY',
                        'State__c' => 'PARENTS_RESIDENTIAL_STATE',
                        'Country__c' => 'PARENTS_RESIDENTIAL_COUNTRY'
                        };
                            
                            public static void processStudentChanges(List<Student__c> newList, Map<Id, Student__c> oldMap) {
                                System.debug('newList---'+ newList + newList.size());
                                List<Programme_Application__c> checkProgApp= new List<Programme_Application__c>();
                                checkProgApp = [SELECT Id FROM Programme_Application__c WHERE Student__c =: newList[0].Id AND EMX_ID__c != null];
                                if(!checkProgApp.isEmpty()){
                                    System.debug('checkProgApp---'+ checkProgApp);
                                    processChanges(newList, oldMap, 'Student__c');
                                }else{
                                    System.debug('No Programme Application found for the Student. So no need to send the details.');
                                }
                            }
    
    
                           public static void processAccountChanges(List<Account> newList, Map<Id, Account> oldMap) {
                                System.debug('newList---'+ newList);
                                processChanges(newList, oldMap, 'Account');
                                // List<Student__c> getStudents = new List<Student__c>();
                                // getStudents = [SELECT Id FROM Student__c WHERE Parent_Account__c =: newList[0].Id];
                                // if(!getStudents.isEmpty()){
                                //     System.debug('getStudents---' + getStudents);
                                //     for(Student__c stud: getStudents){
                                //         List<Programme_Application__c> allProgApp= new List<Programme_Application__c>();
                                //         allProgApp = [SELECT Id, Student__c, EMX_ID__c FROM Programme_Application__c WHERE Student__c =: stud.Id AND EMX_ID__c != null];
                                //         if(!allProgApp.isEmpty()){
                                //             System.debug('allProgApp---'+ allProgApp);
                                //             processChanges(newList, oldMap, 'Account');
                                //         }else{
                                //             System.debug('No Programme Application found for the Student. So no need to send the details.');
                                //         }
                                //     }
                                // }   
                            }
    
    
    
                           private static void processChanges(List<SObject> newList, Map<Id, SObject> oldMap, String objectType) {
                            List<Map<String, Object>> updatedFields = new List<Map<String, Object>>();
        
                                 User currentUser = [SELECT Username, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
        
                             if (currentUser.Profile.Name == 'Minimum Access - API Only Integrations') {
                                 System.debug('Skipping for Minimum Access - API Only Integrations profile');
                                  return;
                             }
        
        
        
                           Set<String> systemFieldsToIgnore = new Set<String>{
                               'LastModifiedDate', 'LastModifiedById', 'SystemModstamp', 'CreatedDate', 'CreatedById'
                              };
                    
                    
                    
                    
                    
                    for (SObject newRec : newList) {
                        
                        SObject oldRec = oldMap.get(newRec.Id);  
                        System.debug('oldRec'+oldRec);
                        if (oldRec == null) continue;
                        
                        Map<String, Object> newRecMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(newRec));
                        Map<String, Object> oldRecMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(oldRec));
                        System.debug('newRecMap'+newRecMap);
                        System.debug('oldRecMap'+oldRecMap);
                        
                        
                        for (String fieldName : newRecMap.keySet()) {
                            if (systemFieldsToIgnore.contains(fieldName)) continue;
                            
                            Object newVal = newRecMap.get(fieldName);
                            Object oldVal = oldRecMap.get(fieldName);
                            if ((newVal != oldVal) && (newVal == null || oldVal == null || !newVal.equals(oldVal))) {
                                
                                String EmxApiName;
                                if (objectType == 'Student__c' && studentFieldMap.containsKey(fieldName)) {
                                    EmxApiName = studentFieldMap.get(fieldName);
                                }else if (objectType == 'Account' && parentFieldMap.containsKey(fieldName)) {
                                    EmxApiName = parentFieldMap.get(fieldName);
                                }else {
                                    continue;
                                }
                                
                                if (objectType == 'Student__c') {
                                     Student__c studentRec = (Student__c)newRec;
                                    Map<String, Object> updatedJson = new Map<String, Object>{
                                        'client_id' => clientID,
                                            'CRM_MODE' => 'STUD_UPDATE',
                                            'CRM_STUD_ID' => studentRec.Id,
                                            'COLUMN_NAME' => EmxApiName,
                                            'NEW_VALUE' => String.valueOf(newVal),
                                            'CRM_ORG_ID' => getOrgId(),
                                            'CRM_CAMPUS_ID' => studentRec.Campus_SFID__c
                                            };
                                            System.debug('CRM_CAMPUS_ID'+studentRec.Campus_SFID__c);    
                                                updatedFields.add(updatedJson);
                                    
                                    
                                } else if (objectType == 'Account') {
                                    List<Student__c> students = getStudentsFromAccount(newRec.Id);
                                    for (Student__c student : students) {
                                        Map<String, Object> updatedJson = new Map<String, Object>{
                                            'client_id' => clientID,
                                                'CRM_MODE' => 'STUD_UPDATE',
                                                'CRM_STUD_ID' => student.Id,
                                                'COLUMN_NAME' => EmxApiName,
                                                'NEW_VALUE' => String.valueOf(newVal),
                                                'CRM_ORG_ID' => getOrgId(),
                                                'CRM_CAMPUS_ID' => student.Campus_SFID__c
                                                };
                                                    updatedFields.add(updatedJson);
                                       
                                    }
                                }
                                
                            }
                        }
                    }
        
        for (Map<String, Object> stdUpdatedJson : updatedFields) {
            String StudentRecordId;
            System.debug('Json->'+stdUpdatedJson);
            if(stdUpdatedJson.containskey('CRM_STUD_ID')){
                StudentRecordId=String.valueOf(stdUpdatedJson.get('CRM_STUD_ID'));
                System.debug('StudentRecordId'+StudentRecordId);
            }
            String jsonPayload = JSON.serialize(stdUpdatedJson);
            System.debug('Final Payload: ' + jsonPayload);
            try{
                SIS_EMXApiCallouts.sendStudentDeatils(jsonPayload,StudentRecordId,'Student');
            }catch (Exception e) {
                System.debug('Failed to send student details: ' + e.getMessage());
            }
        }
        
    }
    
   private static List<Student__c> getStudentsFromAccount(Id accountId) { 
    //List<Student__c> students = [SELECT Id, Campus_SFID__c FROM Student__c WHERE Parent_Account__c = :accountId];
    List<Student__c> students = [SELECT Id, Campus_SFID__c FROM Student__c WHERE Parent_Account__c = :accountId AND Id IN (SELECT Student__c FROM Programme_Application__c WHERE EMX_ID__c != NULL)];
    if (!students.isEmpty()) {
        return students;
    }
    return new List<Student__c>();
}

}