SIS/force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Parent_Email_Address__c</fullName>
    <label>Parent Email Address</label>
    <type>Email</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>Parent_NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Relationship_Father_Mother__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Father_Mother__c</fullName>
    <label>Parent Relationship (Father/Mother)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunty</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Accounts</relationshipLabel>
    <relationshipName>PrimaryAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/recordTypes/Campus_ID.recordType-meta.xml
<RecordType>
    <fullName>Campus_ID</fullName>
    <active>true</active>
    <label>Campus ID</label>
</RecordType>

SIS/force-app/main/default/objects/Contact/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/Programme_Application__c.object-meta.xml
<CustomObject>
    <label>Programme Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Programme Application No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programme Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Programme_Application__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Programme Applications</relationshipLabel>
    <relationshipName>Programme_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/Programme_Master__c.object-meta.xml
<CustomObject>
    <label>Programme Master</label>
    <nameField>
        <label>Programme Master  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Programme_Master__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Student__c/fields/Country_m__c.field-meta.xml
<CustomField>
    <fullName>Country_m__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Country_p__c.field-meta.xml
<CustomField>
    <fullName>Country_p__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorce</fullName>
            </value>
            <value>
                <fullName>Widow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>NRIC/Passport No.</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Postcode_m__c.field-meta.xml
<CustomField>
    <fullName>Postcode_m__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Postcode_p__c.field-meta.xml
<CustomField>
    <fullName>Postcode_p__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAJAU</fullName>
            </value>
            <value>
                <fullName>BIDAYUH</fullName>
            </value>
            <value>
                <fullName>CHINESE</fullName>
            </value>
            <value>
                <fullName>DUSUN</fullName>
            </value>
            <value>
                <fullName>IBAN</fullName>
            </value>
            <value>
                <fullName>INDIAN</fullName>
            </value>
            <value>
                <fullName>KADAZAN</fullName>
            </value>
            <value>
                <fullName>KADAZANDUSUN</fullName>
            </value>
            <value>
                <fullName>MALAY</fullName>
            </value>
            <value>
                <fullName>MELANAU</fullName>
            </value>
            <value>
                <fullName>MURUT</fullName>
            </value>
            <value>
                <fullName>ORANG ASLI</fullName>
            </value>
            <value>
                <fullName>ORANG SUNGAI</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>PUNJABI</fullName>
            </value>
            <value>
                <fullName>SINO-KADAZAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Religion__c.field-meta.xml
<CustomField>
    <fullName>Religion__c</fullName>
    <label>Religion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUDDHIST</fullName>
            </value>
            <value>
                <fullName>CHRISTIAN</fullName>
            </value>
            <value>
                <fullName>HINDU</fullName>
            </value>
            <value>
                <fullName>MUSLIM</fullName>
            </value>
            <value>
                <fullName>SIKH</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/State_m__c.field-meta.xml
<CustomField>
    <fullName>State_m__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/State_p__c.field-meta.xml
<CustomField>
    <fullName>State_p__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Street_m__c.field-meta.xml
<CustomField>
    <fullName>Street_m__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Street_p__c.field-meta.xml
<CustomField>
    <fullName>Street_p__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MELBOURNE</fullName>
    </customValue>
    <customValue>
        <fullName>SYDNEY</fullName>
    </customValue>
    <customValue>
        <fullName>WESTERN AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>BARISAL</fullName>
    </customValue>
    <customValue>
        <fullName>CHITTAGONG</fullName>
    </customValue>
    <customValue>
        <fullName>DHAKA</fullName>
    </customValue>
    <customValue>
        <fullName>BUBANZA</fullName>
    </customValue>
    <customValue>
        <fullName>BUJUMBURA</fullName>
    </customValue>
    <customValue>
        <fullName>BURURI</fullName>
    </customValue>
    <customValue>
        <fullName>CANKUZO</fullName>
    </customValue>
    <customValue>
        <fullName>CIBITOKE</fullName>
    </customValue>
    <customValue>
        <fullName>GITEGA</fullName>
    </customValue>
    <customValue>
        <fullName>KARUZI</fullName>
    </customValue>
    <customValue>
        <fullName>KAYANZA</fullName>
    </customValue>
    <customValue>
        <fullName>KIRUNDO</fullName>
    </customValue>
    <customValue>
        <fullName>MAKAMBA</fullName>
    </customValue>
    <customValue>
        <fullName>MURAMVYA</fullName>
    </customValue>
    <customValue>
        <fullName>MUYINGA</fullName>
    </customValue>
    <customValue>
        <fullName>MWARO</fullName>
    </customValue>
    <customValue>
        <fullName>NGOZI</fullName>
    </customValue>
    <customValue>
        <fullName>RUTANA</fullName>
    </customValue>
    <customValue>
        <fullName>RUYIGI</fullName>
    </customValue>
    <customValue>
        <fullName>ANHUI</fullName>
    </customValue>
    <customValue>
        <fullName>BEIJING</fullName>
    </customValue>
    <customValue>
        <fullName>CHONGQING</fullName>
    </customValue>
    <customValue>
        <fullName>FUJIAN</fullName>
    </customValue>
    <customValue>
        <fullName>GANSU</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGDONG</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGXI</fullName>
    </customValue>
    <customValue>
        <fullName>GUIZHOU</fullName>
    </customValue>
    <customValue>
        <fullName>MALE</fullName>
    </customValue>
    <customValue>
        <fullName>SELANGOR</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

SIS/force-app/main/default/classes/EMXWebServiceForProgramApplicationTest.cls
@isTest
public class EMXWebServiceForProgramApplicationTest {
    @testSetup
    public static void setUpData(){
        // Create Campus
        List<RecordType> rt = new List<RecordType>();
        rt = [Select Id From RecordType Where DeveloperName = 'Campus_ID' LIMIT 1];
        
        Account account = new Account();
        account.RecordTypeId = rt[0].Id;
        account.Name = 'SISJ';
        insert account;
        
        // Parent Account
        Account acc = new Account();
        acc.Name = 'TestName';
        acc.Parent_NRIC_Passport_No__c = '112233445566';
        acc.Parent_Relationship_Father_Mother__c = 'Mother';
        acc.Parent_Email_Address__c = 'xyz@gmail.com';
        acc.Phone = '60456183447';
        acc.Street__c = 'xyz';
        acc.City__c = 'xyz';
        acc.State__c = 'SYDNEY';
        acc.Country__c = 'MY';
        acc.Postcode__c = '756532';
        
        insert acc;
        
        
        // Parent Contact
        Contact con = new Contact();
        con.Primary_Account__c = acc.Id;
        con.LastName = 'TestConName';
        con.Primary_Contact__c = true;
        con.NRIC_Passport_No__c = '0829172';
        con.Email = 'abc@gmail.com';
        con.MobilePhone = '61456183447';
        
        insert con;
        
        
        // Student
        Student__c stud = new Student__c();
        stud.Name = 'TestStudent';
        stud.Parent_Account__c = acc.Id;
        stud.EMX_ID__c = '9874';
        stud.NRIC_Passport_No__c = '789456980765';
        stud.Date_of_Birth__c = Date.today() - 100;
        stud.Primary_Contact__c = con.Id;
        stud.Nationality__c = 'MY';
        stud.Gender__c = 'MALE';
        stud.Marital_Status__c = 'Single';
        stud.Religion__c = 'HINDU';
        stud.State_m__c = 'SELANGOR';
        stud.Country_m__c = 'MY';
        stud.Street_m__c = 'abc street';
        stud.Postcode_m__c = '12345';
        stud.State_p__c = 'SELANGOR';
        stud.Country_p__c = 'MY';
        stud.Street_p__c = 'abc street';
        stud.Postcode_p__c = '12345';
        stud.Race__c = 'OTHERS';
        stud.Lead_Source__c = 'KAKAOTALK';
        stud.Acknowledged_Date__c = Date.today() - 1;
        stud.Campus_SFID__c = account.Id;
        
        insert stud;
        
        
        // Programme Master
        Programme_Master__c pm = new Programme_Master__c();
        pm.EMX_ID__c = '4561';
        pm.Name = 'Testpm';
        pm.Programme_Code__c = '1111';
        pm.Programme_Duration__c = 12;
        pm.Level_of_Education__c = 'Primary';
        pm.Is_Offer__c = 'y';
        pm.Campus_SFID__c = account.Id;
        pm.Campus_Code__c = '8520';
        pm.Campus_Name__c = 'SISKL';
        pm.Campus_Location__c = 'Malaysia';
        pm.School_Code__c = '156321';
        
        insert pm;
        
        // Intake Master
        Intake_Master__c im = new Intake_Master__c();
        im.EMX_ID__c = '7532';
        im.Programme_Master__c = pm.Id;
        im.Intake_Number__c = '789456123';
        im.Study_Mode__c = 'Online';
        im.Course_Detail_Intake_ID__c = 123987;
        im.Application_Allowed__c = 'YES';
        
        insert im;
        
        
        // Programme Application
        Programme_Application__c pa = new Programme_Application__c();
        pa.EMX_ID__c = '1234';
        pa.Offer_Status__c = 'Pending For Approval';
        pa.Student__c = stud.Id;
        pa.Programme_Master__c = pm.Id;
        pa.Intake_Master__c = im.Id;
        pa.Application_Type__c = 'NEW';
        
        insert pa;
        
    }
    
    @isTest
    public static void testUpdateProgramApplication(){
        
        Programme_Application__c pa = [SELECT Id FROM Programme_Application__c LIMIT 1];
        Student__c stud = [SELECT Id FROM Student__c LIMIT 1];
        Programme_Master__c pm = [SELECT Id FROM Programme_Master__c LIMIT 1];
        Intake_Master__c im = [SELECT Id FROM Intake_Master__c LIMIT 1];
        
        
        Map<String, Object> programApplication = new Map<String, Object>();
        programApplication.put('eMXID', '7782');
        programApplication.put('CRMProgramApplicationID', pa.Id);
        programApplication.put('offerStatus', 'Cancelled');
        programApplication.put('conditionalCode', '31d32');
        programApplication.put('offerLetterPrintedDate', '2025-02-15');
        programApplication.put('acceptanceDate', '2025-01-15');
        programApplication.put('immigrationPassType', 'Online');
        programApplication.put('immigrationPassExpiryDate', null);
        programApplication.put('immigrationPassInstitutionName', 'jSP');
        programApplication.put('CRMStudentID', stud.Id);
        programApplication.put('CRMProgrammeMasterID', pm.Id);
        programApplication.put('CRMIntakeMasterID', im.Id);
        
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('programApplication', programApplication);
        
        
        String requestBody = JSON.serialize(requestBodyMap);
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        EMXWebServiceForProgramApplication.updateProgramApplication();
        Test.stopTest();
    }
    
    @isTest
    public static void testUpdateProgramApplicationWithWrongIMId(){
        
        Programme_Application__c pa = [SELECT Id FROM Programme_Application__c LIMIT 1];
        Student__c stud = [SELECT Id FROM Student__c LIMIT 1];
        Programme_Master__c pm = [SELECT Id FROM Programme_Master__c LIMIT 1];
        Intake_Master__c im = [SELECT Id FROM Intake_Master__c LIMIT 1];
        
        
        Map<String, Object> programApplication = new Map<String, Object>();
        programApplication.put('eMXID', '7782');
        programApplication.put('CRMProgramApplicationID', pa.Id);
        programApplication.put('offerStatus', 'Cancelled');
        programApplication.put('conditionalCode', '31d32');
        programApplication.put('offerLetterPrintedDate', '2025-02-15');
        programApplication.put('acceptanceDate', '2025-01-15');
        programApplication.put('immigrationPassType', 'Online');
        programApplication.put('immigrationPassExpiryDate', null);
        programApplication.put('immigrationPassInstitutionName', 'jSP');
        programApplication.put('CRMStudentID', stud.Id);
        programApplication.put('CRMProgrammeMasterID', pm.Id);
        programApplication.put('CRMIntakeMasterID', 'X' + String.valueOf(pm.Id).substring(1));
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('programApplication', programApplication);
        
        
        String requestBody = JSON.serialize(requestBodyMap);
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        EMXWebServiceForProgramApplication.updateProgramApplication();
        Test.stopTest();
    }
    
    @isTest
    public static void testMissingFieldsProgramApplication(){
        
        Programme_Application__c pa = [SELECT Id FROM Programme_Application__c LIMIT 1];
        Student__c stud = [SELECT Id FROM Student__c LIMIT 1];
        Programme_Master__c pm = [SELECT Id FROM Programme_Master__c LIMIT 1];
        Intake_Master__c im = [SELECT Id FROM Intake_Master__c LIMIT 1];
        
        
        Map<String, Object> programApplication = new Map<String, Object>();
        programApplication.put('eMXID', '7782');
        programApplication.put('CRMProgramApplicationID', pa.Id);
        programApplication.put('offerStatus', 'Cancelled');
        programApplication.put('conditionalCode', '31d32');
        programApplication.put('offerLetterPrintedDate', '2025-02-15');
        programApplication.put('acceptanceDate', '2025-01-15');
        programApplication.put('immigrationPassType', 'Online');
        programApplication.put('immigrationPassExpiryDate', null);
        programApplication.put('immigrationPassInstitutionName', 'jSP');
        programApplication.put('CRMStudentID', '');
        programApplication.put('CRMProgrammeMasterID', pm.Id);
        programApplication.put('CRMIntakeMasterID', '');
        
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('programApplication', programApplication);
        
        
        String requestBody = JSON.serialize(requestBodyMap);
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        EMXWebServiceForProgramApplication.updateProgramApplication();
        Test.stopTest();    
    }
    
    @isTest
    public static void testMissingIntakeFieldsProgramApplication(){
        
        Student__c stud = [SELECT Id FROM Student__c LIMIT 1];
        Programme_Master__c pm = [SELECT Id FROM Programme_Master__c LIMIT 1];
        
        Map<String, Object> programApplication = new Map<String, Object>();
        programApplication.put('eMXID', '7782');
        programApplication.put('CRMProgramApplicationID', '');
        programApplication.put('offerStatus', 'Cancelled');
        programApplication.put('conditionalCode', '31d32');
        programApplication.put('offerLetterPrintedDate', '2025-02-15');
        programApplication.put('acceptanceDate', '2025-01-15');
        programApplication.put('immigrationPassType', 'Online');
        programApplication.put('immigrationPassExpiryDate', null);
        programApplication.put('immigrationPassInstitutionName', 'jSP');
        programApplication.put('CRMStudentID', stud.Id);
        programApplication.put('CRMProgrammeMasterID', pm.Id);
        programApplication.put('CRMIntakeMasterID', '');
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('programApplication', programApplication);
        
        String requestBody = JSON.serialize(requestBodyMap);
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        EMXWebServiceForProgramApplication.updateProgramApplication();
        Test.stopTest();    
    }
    
    
}