SIS/force-app/main/default/objects/Account/fields/Parent_NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>Parent_NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Relationship_Father_Mother__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Father_Mother__c</fullName>
    <label>Parent Relationship (Father/Mother)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunty</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Accounts</relationshipLabel>
    <relationshipName>PrimaryAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Application_For_Admissions_Form__c.field-meta.xml
<CustomField>
    <fullName>Application_For_Admissions_Form__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Application For Admissions Form</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Initial_Application_Fee__c.field-meta.xml
<CustomField>
    <fullName>Initial_Application_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initial Application Fee</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Is_Duplicate_Student__c.field-meta.xml
<CustomField>
    <fullName>Is_Duplicate_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Duplicate Student?</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Leads</relationshipLabel>
    <relationshipName>Child_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Parent_Lead__c.field-meta.xml
<CustomField>
    <fullName>Parent_Lead__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Lead</label>
    <referenceTo>Parent_Lead__c</referenceTo>
    <relationshipLabel>Child Leads</relationshipLabel>
    <relationshipName>Child_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Passport_IC__c.field-meta.xml
<CustomField>
    <fullName>Passport_IC__c</fullName>
    <label>Passport/ IC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Post_Application_Received__c.field-meta.xml
<CustomField>
    <fullName>Post_Application_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Post Application Email Received</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Lead/fields/Supporting_Document_Submission__c.field-meta.xml
<CustomField>
    <fullName>Supporting_Document_Submission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Supporting Document Submission</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/Parent_Lead__c.object-meta.xml
<CustomObject>
    <label>Parent Lead</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parent Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Campus__c.field-meta.xml
<CustomField>
    <fullName>Campus__c</fullName>
    <label>Campus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SISKL</fullName>
            </value>
            <value>
                <fullName>SISJB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Mobile_Number_1__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_1__c</fullName>
    <label>Mobile Number 1</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Parent_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship__c</fullName>
    <label>Parent Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunty</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Parent_Lead__c/fields/Passport_IC__c.field-meta.xml
<CustomField>
    <fullName>Passport_IC__c</fullName>
    <label>Passport/ IC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/classes/SISLeadConversionControllerTest.cls
@isTest
public with sharing class SISLeadConversionControllerTest {
    @testSetup
    public static void setUpData(){
        //Create Parent Lead
        Parent_Lead__c pl = new Parent_Lead__c();
        pl.Name = 'TestParentLead';
        pl.Campus__c = 'SIS';
        pl.Email__c = 'test@gmail.com';
        pl.Mobile_Number_1__c = '1234567890';
        pl.Passport_IC__c = '112233445566';
        pl.Parent_Relationship__c = 'Father';
        insert pl;
        
        //Child Lead with parent lead
        Lead l = new Lead();
        l.LastName = 'testchildLead';
        l.Status = 'new';
        l.Date_of_Birth__c = Date.today()-1;
        l.Parent_Lead__c = pl.Id;
        l.Passport_IC__c = '123123123123';
        l.Application_For_Admissions_Form__c = true;
        l.Initial_Application_Fee__c = true;
        l.Supporting_Document_Submission__c = true;
        l.Post_Application_Received__c = true;
        insert l;
        
        Lead lead = new Lead();
        lead.LastName = 'testchildLead123';
        lead.Status = 'New';
        lead.Date_of_Birth__c = Date.today()-5;
        lead.Parent_Lead__c = pl.Id;
        lead.Passport_IC__c = '123123123125';
        lead.Application_For_Admissions_Form__c = true;
        lead.Initial_Application_Fee__c = true;
        lead.Supporting_Document_Submission__c = true;
        lead.Post_Application_Received__c = true;
        insert lead;
        
        //Create Account
        Account acc = new Account();
        acc.Name = 'TestName';
        acc.Parent_NRIC_Passport_No__c = '112233445566';
        acc.Parent_Relationship_Father_Mother__c = 'Father';
        insert acc;
        
        //Create Contact
        Contact con = new Contact();
        con.Primary_Account__c = acc.Id;
        con.LastName = 'TestConName';
        con.Primary_Contact__c = true;
        con.NRIC_Passport_No__c = '112233445566';
        insert con;
        
        //Child Lead with parent account
        Lead le = new Lead();
        le.LastName = 'testchildLead1';
        le.Status = 'new';
        le.Date_of_Birth__c = Date.today()-1;
        le.Parent_Account__c = acc.Id;
        le.Passport_IC__c = '123123123123';
        le.Application_For_Admissions_Form__c = true;
        le.Initial_Application_Fee__c = true;
        le.Supporting_Document_Submission__c = true;
        le.Post_Application_Received__c = true;
        le.Is_Duplicate_Student__c = true;
        insert le;
        
        //Child Lead for handleIsDuplicate
        
        Lead le1 = new Lead();
        le1.LastName = 'childLeadforDuplicateTrue';
        le1.Status = 'new';
        le1.Date_of_Birth__c = Date.today()-1;
        le1.Parent_Account__c = acc.Id;
        le1.Passport_IC__c = '123123123123';
        le1.Application_For_Admissions_Form__c = true;
        le1.Initial_Application_Fee__c = true;
        le1.Supporting_Document_Submission__c = true;
        le1.Post_Application_Received__c = true;
        le1.Is_Duplicate_Student__c = true;
        insert le1;
        
        Lead le2 = new Lead();
        le2.LastName = 'childLeadforDuplicateFalse';
        le2.Status = 'new';
        le2.Date_of_Birth__c = Date.today()-1;
        le2.Parent_Account__c = acc.Id;
        le2.Passport_IC__c = '123123123123';
        le2.Application_For_Admissions_Form__c = true;
        le2.Initial_Application_Fee__c = true;
        le2.Supporting_Document_Submission__c = true;
        le2.Post_Application_Received__c = true;
        le2.Is_Duplicate_Student__c = true;
        insert le2;
    }
    
    @isTest
    public static void getLeadConvertDetailsAndConvertLeadTest(){
        String leadIdwithPL = [SELECT Id FROM Lead WHERE Name = 'testchildLead' LIMIT 1].Id;
                
        Test.startTest();
        
        Map<String, Object> leadDetailswithPL = SISLeadConversionController.getLeadConvertDetails(leadIdwithPL);
        Map<String, Object> convertDetailswithPL = SISLeadConversionController.convertLead(leadIdwithPL);
        
        Test.stopTest();
    }
    
    @isTest
    public static void getLeadConvertDetailsAndConvertLeadTestForAcc(){
        String leadIdwithPA = [SELECT Id FROM Lead WHERE Name = 'testchildLead1' LIMIT 1].Id;
        String leadIdwithDuplicateTrue = [SELECT Id FROM Lead WHERE Name = 'childLeadforDuplicateTrue' LIMIT 1].Id;
        String leadIdwithDuplicateFalse = [SELECT Id FROM Lead WHERE Name = 'childLeadforDuplicateFalse' LIMIT 1].Id;
        Test.startTest();
        Map<String, Object> leadDetailswithPA = SISLeadConversionController.getLeadConvertDetails(leadIdwithPA);
        Map<String, Object> convertDetailswithPA = SISLeadConversionController.convertLead(leadIdwithPA);
        
        Map<String, Object> handleIsDuplicateTrue = SISLeadConversionController.handleIsDuplicate(leadIdwithDuplicateTrue);
        Map<String, Object> handleIsDuplicateFalse = SISLeadConversionController.handleIsDuplicate(leadIdwithDuplicateFalse);
        Test.stopTest();
    }
    
    
}