SIS/force-app/main/default/objects/Account/fields/Parent_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Parent_Email_Address__c</fullName>
    <label>Parent Email Address</label>
    <type>Email</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>Parent_NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Relationship_Father_Mother__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Father_Mother__c</fullName>
    <label>Parent Relationship (Father/Mother)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunty</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Accounts</relationshipLabel>
    <relationshipName>PrimaryAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Account/recordTypes/Campus_ID.recordType-meta.xml
<RecordType>
    <fullName>Campus_ID</fullName>
    <active>true</active>
    <label>Campus ID</label>
</RecordType>

SIS/force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Intake_Master__c/Intake_Master__c.object-meta.xml
<CustomObject>
    <label>Intake Master</label>
    <nameField>
        <displayFormat>IM-{00000}</displayFormat>
        <label>Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intake Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Intake_Master__c/fields/Programme_Master__c.field-meta.xml
<CustomField>
    <fullName>Programme_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme Master</label>
    <referenceTo>Programme_Master__c</referenceTo>
    <relationshipLabel>Intake Masters</relationshipLabel>
    <relationshipName>Intake_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Application__c/Programme_Application__c.object-meta.xml
<CustomObject>
    <label>Programme Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Programme Application No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programme Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Programme_Application__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Programme Applications</relationshipLabel>
    <relationshipName>Programme_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Programme_Master__c/Programme_Master__c.object-meta.xml
<CustomObject>
    <label>Programme Master</label>
    <nameField>
        <label>Programme Master  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programme Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Programme_Master__c/fields/Campus_SFID__c.field-meta.xml
<CustomField>
    <fullName>Campus_SFID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campus SFID</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please Select a Valid Campus</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Campus_ID</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programme Masters</relationshipLabel>
    <relationshipName>Programme_Masters</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Student__c/fields/Campus_SFID__c.field-meta.xml
<CustomField>
    <fullName>Campus_SFID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campus SFID</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please Select a Valid Campus.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Campus_ID</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Country_m__c.field-meta.xml
<CustomField>
    <fullName>Country_m__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Country_p__c.field-meta.xml
<CustomField>
    <fullName>Country_p__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FACEBOOK</fullName>
            </value>
            <value>
                <fullName>INSTAGRAM</fullName>
            </value>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>TAWK-TO-CHAT</fullName>
            </value>
            <value>
                <fullName>WECHAT</fullName>
            </value>
            <value>
                <fullName>KAKAOTALK</fullName>
            </value>
            <value>
                <fullName>OPEN DAY &amp; INFO DAY</fullName>
            </value>
            <value>
                <fullName>PHONE INQUIRY</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorce</fullName>
            </value>
            <value>
                <fullName>Widow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>NRIC/Passport No.</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Postcode_m__c.field-meta.xml
<CustomField>
    <fullName>Postcode_m__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Postcode_p__c.field-meta.xml
<CustomField>
    <fullName>Postcode_p__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAJAU</fullName>
            </value>
            <value>
                <fullName>BIDAYUH</fullName>
            </value>
            <value>
                <fullName>CHINESE</fullName>
            </value>
            <value>
                <fullName>DUSUN</fullName>
            </value>
            <value>
                <fullName>IBAN</fullName>
            </value>
            <value>
                <fullName>INDIAN</fullName>
            </value>
            <value>
                <fullName>KADAZAN</fullName>
            </value>
            <value>
                <fullName>KADAZANDUSUN</fullName>
            </value>
            <value>
                <fullName>MALAY</fullName>
            </value>
            <value>
                <fullName>MELANAU</fullName>
            </value>
            <value>
                <fullName>MURUT</fullName>
            </value>
            <value>
                <fullName>ORANG ASLI</fullName>
            </value>
            <value>
                <fullName>ORANG SUNGAI</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>PUNJABI</fullName>
            </value>
            <value>
                <fullName>SINO-KADAZAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Religion__c.field-meta.xml
<CustomField>
    <fullName>Religion__c</fullName>
    <label>Religion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUDDHIST</fullName>
            </value>
            <value>
                <fullName>CHRISTIAN</fullName>
            </value>
            <value>
                <fullName>HINDU</fullName>
            </value>
            <value>
                <fullName>MUSLIM</fullName>
            </value>
            <value>
                <fullName>SIKH</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/State_m__c.field-meta.xml
<CustomField>
    <fullName>State_m__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/State_p__c.field-meta.xml
<CustomField>
    <fullName>State_p__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Street_m__c.field-meta.xml
<CustomField>
    <fullName>Street_m__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Street_p__c.field-meta.xml
<CustomField>
    <fullName>Street_p__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MELBOURNE</fullName>
    </customValue>
    <customValue>
        <fullName>SYDNEY</fullName>
    </customValue>
    <customValue>
        <fullName>WESTERN AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>BARISAL</fullName>
    </customValue>
    <customValue>
        <fullName>CHITTAGONG</fullName>
    </customValue>
    <customValue>
        <fullName>DHAKA</fullName>
    </customValue>
    <customValue>
        <fullName>BUBANZA</fullName>
    </customValue>
    <customValue>
        <fullName>BUJUMBURA</fullName>
    </customValue>
    <customValue>
        <fullName>BURURI</fullName>
    </customValue>
    <customValue>
        <fullName>CANKUZO</fullName>
    </customValue>
    <customValue>
        <fullName>CIBITOKE</fullName>
    </customValue>
    <customValue>
        <fullName>GITEGA</fullName>
    </customValue>
    <customValue>
        <fullName>KARUZI</fullName>
    </customValue>
    <customValue>
        <fullName>KAYANZA</fullName>
    </customValue>
    <customValue>
        <fullName>KIRUNDO</fullName>
    </customValue>
    <customValue>
        <fullName>MAKAMBA</fullName>
    </customValue>
    <customValue>
        <fullName>MURAMVYA</fullName>
    </customValue>
    <customValue>
        <fullName>MUYINGA</fullName>
    </customValue>
    <customValue>
        <fullName>MWARO</fullName>
    </customValue>
    <customValue>
        <fullName>NGOZI</fullName>
    </customValue>
    <customValue>
        <fullName>RUTANA</fullName>
    </customValue>
    <customValue>
        <fullName>RUYIGI</fullName>
    </customValue>
    <customValue>
        <fullName>ANHUI</fullName>
    </customValue>
    <customValue>
        <fullName>BEIJING</fullName>
    </customValue>
    <customValue>
        <fullName>CHONGQING</fullName>
    </customValue>
    <customValue>
        <fullName>FUJIAN</fullName>
    </customValue>
    <customValue>
        <fullName>GANSU</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGDONG</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGXI</fullName>
    </customValue>
    <customValue>
        <fullName>GUIZHOU</fullName>
    </customValue>
    <customValue>
        <fullName>MALE</fullName>
    </customValue>
    <customValue>
        <fullName>SELANGOR</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

SIS/force-app/main/default/classes/SIS_JsonForProgrammeApplicationTest.cls
@isTest
public class SIS_JsonForProgrammeApplicationTest {
    @TestSetup
    public static void setUpDate(){
        // Create Campus
        List<RecordType> rt = new List<RecordType>();
        rt = [Select Id From RecordType Where DeveloperName = 'Campus_ID' LIMIT 1];
        
        Account account = new Account();
        account.RecordTypeId = rt[0].Id;
        account.Name = 'SISJ';
        insert account;
        
        //Create Account
        Account acc = new Account();
        acc.Name = 'testAcc';
        acc.Parent_NRIC_Passport_No__c = '154789654123';
        acc.Parent_Relationship_Father_Mother__c = 'Father';
        acc.Parent_Email_Address__c = 'testacc@gmail.com';
        insert acc;
        
        //Create Contact
        Contact con = new Contact();
        con.LastName = 'testCon';
        con.NRIC_Passport_No__c = '154789654123';
        con.Primary_Account__c = acc.Id;
        con.Email = 'testcon@gmail.com';
        insert con;
        
        //Create Student
        Student__c stud = new Student__c();
        stud.Name = 'testStud';
        stud.NRIC_Passport_No__c = '154578451215';
        stud.Date_of_Birth__c = Date.Today()-500;
        stud.Parent_Account__c = acc.Id;
        stud.Primary_Contact__c = con.Id;
        stud.Nationality__c = 'MY';
        stud.Gender__c = 'MALE';
        stud.Marital_Status__c = 'Single';
        stud.Religion__c = 'HINDU';
        stud.State_m__c = 'SELANGOR';
        stud.Country_m__c = 'MY';
        stud.Street_m__c = 'abc street';
        stud.Postcode_m__c = '12345';
        stud.State_p__c = 'SELANGOR';
        stud.Country_p__c = 'MY';
        stud.Street_p__c = 'abc street';
        stud.Postcode_p__c = '12345';
        stud.Race__c = 'OTHERS';
        stud.Lead_Source__c = 'KAKAOTALK';
        stud.Acknowledged_Date__c = date.Today()-1;
        stud.Campus_SFID__c = account.Id;
        insert stud;
        
        //Create Programme_Master__c
        Programme_Master__c proMaster = new Programme_Master__c();
        proMaster.Name = 'proName';
        proMaster.Programme_Code__c = 'SIS0012';
        proMaster.Programme_Duration__c = 12;
        proMaster.Level_of_Education__c = 'Primary';
        proMaster.Is_Offer__c = 'Yes';
        proMaster.Campus_SFID__c = account.Id;
        proMaster.Campus_Code__c = '159753';
        proMaster.Campus_Name__c = 'SISKL';
        proMaster.Campus_Location__c = 'Malaysia';
        proMaster.School_Code__c = '156321';
        insert proMaster;
        
        //Create Intake Master
        Intake_Master__c intMaster = new Intake_Master__c();
        intMaster.Intake_Number__c = '789456123';
        intMaster.Study_Mode__c = 'Online';
        intMaster.Course_Detail_Intake_ID__c = 123987;
        intMaster.Application_Allowed__c = 'YES';
        intMaster.Programme_Master__c = proMaster.Id;
        insert intMaster;
        
        //Create Programme_Application__c
        Programme_Application__c progApp = new Programme_Application__c();
        progApp.Offer_Status__c = 'Pending For Approval';
        progApp.Application_Type__c = 'NEW';
        progApp.Conditional_Code__c = 'codeTest';
        progApp.Student__c = stud.Id;
        progApp.Programme_Master__c = proMaster.Id;
        progApp.Intake_Master__c = intMaster.Id;
        insert progApp;
    }
    
    public class SIS_EMXHttpMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            
            if (req.getEndpoint().contains('/auth/code')) {
                res.setStatusCode(200);
                res.setBody('{"code": "6626f9dc978f311fb71286bf3cf3251c"}');
            } else if (req.getEndpoint().contains('/auth/token')) {
                res.setStatusCode(200);
                res.setBody('{"access": "7a6cf334f796fa14920c35ee2b3b5f00"}');
            } else if (req.getEndpoint().contains('/crm')) {
                res.setStatusCode(200);
                res.setBody('{"transaction_id": "123456"}');
            }
            
            return res;
        }
    }
    
    @isTest
    public static void createJsonForProgrammeApplicationTest(){
        List<Programme_Application__c> progApp = [SELECT Id FROM Programme_Application__c WHERE Conditional_Code__c = 'codeTest' AND Application_Type__c = 'NEW' LIMIT 1];
        Test.startTest();
        SIS_JsonForProgrammeApplication.createJsonForProgrammeApplication(progApp);
        Test.setMock(HttpCalloutMock.class, new SIS_EMXHttpMock());
        Test.stopTest();
    }
    
    
}