SIS/force-app/main/default/objects/Account/fields/Parent_NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>Parent_NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Parent_Relationship_Father_Mother__c.field-meta.xml
<CustomField>
    <fullName>Parent_Relationship_Father_Mother__c</fullName>
    <label>Parent Relationship (Father/Mother)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunty</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Account/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Accounts</relationshipLabel>
    <relationshipName>PrimaryAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Student__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>NRIC/Passport No.</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/classes/EMXWebServiceForStudentTest.cls
@isTest
public with sharing class EMXWebServiceForStudentTest {
    @testSetup
    public static void setUpData(){
        //Create Account
        Account acc = new Account();
        acc.Name = 'TestName';
        acc.Parent_NRIC_Passport_No__c = '112233445566';
        acc.Parent_Relationship_Father_Mother__c = 'Father';
        insert acc;
        
        //Create Contact
        Contact con = new Contact();
        con.Primary_Account__c = acc.Id;
        con.LastName = 'TestConName';
        con.Primary_Contact__c = true;
        con.NRIC_Passport_No__c = '112233445566';
        insert con;
        
        //Create Student
        Student__c stud = new Student__c();
        stud.Name = 'TestStudName';
        stud.Parent_Account__c = acc.Id;
        stud.NRIC_Passport_No__c = '123789';
        stud.Date_of_Birth__c = Date.today() - 100;
        insert stud;
    }
    
    @isTest
    public static void updateStudentTest(){
        String accId = [SELECT Id FROM Account WHERE Name = 'TestName' LIMIT 1].Id;
        String conId = [SELECT Id FROM Contact WHERE Name = 'TestConName' LIMIT 1].Id;
        String studId = [SELECT Id FROM Student__c WHERE Name = 'TestStudName' LIMIT 1].Id;
        
        Map<String, Object> studentMap = new Map<String, Object>();
        studentMap.put('CRMStudentID', studId);
        studentMap.put('studentUID', 'abcd1234');
        studentMap.put('EMXID', 'abcdef123456');
        studentMap.put('name', 'Sanjai');
        studentMap.put('preferredName', 'Sanjai B');
        studentMap.put('nricOrPassportNo', '123456789012');
        studentMap.put('passportExpiryDate', '2026-03-26');
        studentMap.put('dateOfBirth', '2001-03-26');
        studentMap.put('nationality', 'IN');
        studentMap.put('citizenship', 'Malaysian');
        studentMap.put('gender', 'Male');
        studentMap.put('maritalStatus', 'Single');
        studentMap.put('race', 'Others');
        studentMap.put('religion', 'Hindu');
        studentMap.put('studentMobileNo', '9988776655');
        studentMap.put('emailAddress', 'sanjai@gmail.com');
        studentMap.put('mailingStreet', 'abc street');
        studentMap.put('mailingPostCode', '636636');
        studentMap.put('mailingCity', 'Malaysia');
        studentMap.put('mailingState', 'SELANGOR');
        studentMap.put('mailingCountry', 'MY');
        studentMap.put('mailingConTelNo', '3366554488');
        studentMap.put('permanentStreet', 'abc street');
        studentMap.put('permanentPostCode', '636636');
        studentMap.put('permanentCity', 'Malaysia');
        studentMap.put('permanentState', 'SELANGOR');
        studentMap.put('permanentCountry', 'MY');
        studentMap.put('permanentConTelNo', '3366554488');
        studentMap.put('CRMHouseholdID', accId);
        
        // Create outer map
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('student', studentMap);
        
        // Serialize the full map
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        // Mocking request and response
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        
        EMXWebServiceForStudent.updateStudent();
        
        Test.stopTest();
    }
    
    @isTest
    public static void coverException(){
        String accId = [SELECT Id FROM Account WHERE Name = 'TestName' LIMIT 1].Id;
        String conId = [SELECT Id FROM Contact WHERE Name = 'TestConName' LIMIT 1].Id;
        String studId = [SELECT Id FROM Student__c WHERE Name = 'TestStudName' LIMIT 1].Id;
        
        Map<String, Object> studentMap = new Map<String, Object>(); 
        studentMap.put('name', 'Sanjai');
        studentMap.put('nricOrPassportNo', '123456789012');
        studentMap.put('dateOfBirth', '2001-03-26');
        
        // Create outer map
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        requestBodyMap.put('student', studentMap);
        
        // Serialize the full map
        String requestBody = JSON.serialize(requestBodyMap);
        
        Test.startTest();
        // Mocking request and response
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(requestBody);
        RestContext.request = req;
        RestContext.response = res;
        
        EMXWebServiceForStudent.updateStudent();
        
        Test.stopTest();
    }
   
}