SIS/force-app/main/default/objects/Account/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Accounts</relationshipLabel>
    <relationshipName>PrimaryAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>Parent NRIC/Passport No</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SIS/force-app/main/default/objects/Student__c/fields/City_m__c.field-meta.xml
<CustomField>
    <fullName>City_m__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/City_p__c.field-meta.xml
<CustomField>
    <fullName>City_p__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Contact_Telephone_No_m__c.field-meta.xml
<CustomField>
    <fullName>Contact_Telephone_No_m__c</fullName>
    <label>Contact Telephone No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Contact_Telephone_No_p__c.field-meta.xml
<CustomField>
    <fullName>Contact_Telephone_No_p__c</fullName>
    <label>Contact Telephone No.</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Country_m__c.field-meta.xml
<CustomField>
    <fullName>Country_m__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Country_p__c.field-meta.xml
<CustomField>
    <fullName>Country_p__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/EMX_ID__c.field-meta.xml
<CustomField>
    <fullName>EMX_ID__c</fullName>
    <label>EMX ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorce</fullName>
            </value>
            <value>
                <fullName>Widow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/NRIC_Passport_No__c.field-meta.xml
<CustomField>
    <fullName>NRIC_Passport_No__c</fullName>
    <label>NRIC/Passport No.</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Passport_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Passport_Expiry_Date__c</fullName>
    <label>Passport Expiry Date</label>
    <type>Date</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Postcode_m__c.field-meta.xml
<CustomField>
    <fullName>Postcode_m__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Postcode_p__c.field-meta.xml
<CustomField>
    <fullName>Postcode_p__c</fullName>
    <label>Postcode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Name__c</fullName>
    <label>Preferred Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAJAU</fullName>
            </value>
            <value>
                <fullName>BIDAYUH</fullName>
            </value>
            <value>
                <fullName>CHINESE</fullName>
            </value>
            <value>
                <fullName>DUSUN</fullName>
            </value>
            <value>
                <fullName>IBAN</fullName>
            </value>
            <value>
                <fullName>INDIAN</fullName>
            </value>
            <value>
                <fullName>KADAZAN</fullName>
            </value>
            <value>
                <fullName>KADAZANDUSUN</fullName>
            </value>
            <value>
                <fullName>MALAY</fullName>
            </value>
            <value>
                <fullName>MELANAU</fullName>
            </value>
            <value>
                <fullName>MURUT</fullName>
            </value>
            <value>
                <fullName>ORANG ASLI</fullName>
            </value>
            <value>
                <fullName>ORANG SUNGAI</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>PUNJABI</fullName>
            </value>
            <value>
                <fullName>SINO-KADAZAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Religion__c.field-meta.xml
<CustomField>
    <fullName>Religion__c</fullName>
    <label>Religion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUDDHIST</fullName>
            </value>
            <value>
                <fullName>CHRISTIAN</fullName>
            </value>
            <value>
                <fullName>HINDU</fullName>
            </value>
            <value>
                <fullName>MUSLIM</fullName>
            </value>
            <value>
                <fullName>SIKH</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/State_m__c.field-meta.xml
<CustomField>
    <fullName>State_m__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/State_p__c.field-meta.xml
<CustomField>
    <fullName>State_p__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Street_m__c.field-meta.xml
<CustomField>
    <fullName>Street_m__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Street_p__c.field-meta.xml
<CustomField>
    <fullName>Street_p__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Student_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Student_Mobile_No__c</fullName>
    <label>Student Mobile No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Student_SFID__c.field-meta.xml
<CustomField>
    <fullName>Student_SFID__c</fullName>
    <formula>CASESAFEID( Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CRM Student ID</label>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/objects/Student__c/fields/Student_UID__c.field-meta.xml
<CustomField>
    <fullName>Student_UID__c</fullName>
    <label>Student UID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

SIS/force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MELBOURNE</fullName>
    </customValue>
    <customValue>
        <fullName>SYDNEY</fullName>
    </customValue>
    <customValue>
        <fullName>WESTERN AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>BARISAL</fullName>
    </customValue>
    <customValue>
        <fullName>CHITTAGONG</fullName>
    </customValue>
    <customValue>
        <fullName>DHAKA</fullName>
    </customValue>
    <customValue>
        <fullName>BUBANZA</fullName>
    </customValue>
    <customValue>
        <fullName>BUJUMBURA</fullName>
    </customValue>
    <customValue>
        <fullName>BURURI</fullName>
    </customValue>
    <customValue>
        <fullName>CANKUZO</fullName>
    </customValue>
    <customValue>
        <fullName>CIBITOKE</fullName>
    </customValue>
    <customValue>
        <fullName>GITEGA</fullName>
    </customValue>
    <customValue>
        <fullName>KARUZI</fullName>
    </customValue>
    <customValue>
        <fullName>KAYANZA</fullName>
    </customValue>
    <customValue>
        <fullName>KIRUNDO</fullName>
    </customValue>
    <customValue>
        <fullName>MAKAMBA</fullName>
    </customValue>
    <customValue>
        <fullName>MURAMVYA</fullName>
    </customValue>
    <customValue>
        <fullName>MUYINGA</fullName>
    </customValue>
    <customValue>
        <fullName>MWARO</fullName>
    </customValue>
    <customValue>
        <fullName>NGOZI</fullName>
    </customValue>
    <customValue>
        <fullName>RUTANA</fullName>
    </customValue>
    <customValue>
        <fullName>RUYIGI</fullName>
    </customValue>
    <customValue>
        <fullName>ANHUI</fullName>
    </customValue>
    <customValue>
        <fullName>BEIJING</fullName>
    </customValue>
    <customValue>
        <fullName>CHONGQING</fullName>
    </customValue>
    <customValue>
        <fullName>FUJIAN</fullName>
    </customValue>
    <customValue>
        <fullName>GANSU</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGDONG</fullName>
    </customValue>
    <customValue>
        <fullName>GUANGXI</fullName>
    </customValue>
    <customValue>
        <fullName>GUIZHOU</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

SIS/force-app/main/default/classes/EMXWebServiceForStudent.cls
@RestResource(urlMapping='/student/*')
global class EMXWebServiceForStudent {
    public class MyException extends Exception {}

    @HttpPatch
    global static void updateStudent(){
        
        Map<string,object> resultMsg = new Map<string,object>();
        Map<string,Map<string,object>> resultMap = new Map<string,Map<string,object>>();
        
        Boolean isUpdate  = false;
        
        RestResponse res = RestContext.response;
        System.debug('res---'+ res);
        
         RestRequest req = RestContext.request;
        
        try{
           // RestRequest req = RestContext.request;
            System.debug('req---'+ req);
            
            if( req != null && req.requestBody != null ){
                string requestBody = req.requestBody.toString();
                System.debug('requestBody---'+ requestBody);
                Map<String, Object> requestMap = (Map<String, Object>) JSON.deserializeUntyped(requestBody);
                System.debug('requestMap---'+ requestMap);
                Map<String, Object> studentMap = (Map<String, Object>) requestMap.get('student');
                Object dateOfBirth = studentMap.get('dateOfBirth');
                dateOfBirth = dateOfBirth != null ? dateOfBirth : null;
                studentMap.put('dateOfBirth', dateOfBirth);
                Object passportExpiryDate = studentMap.get('passportExpiryDate');
                passportExpiryDate = passportExpiryDate != null ? passportExpiryDate : null;
                studentMap.put('passportExpiryDate', passportExpiryDate);
                requestMap.put('student', studentMap);
                System.debug('requestMap---'+ requestMap);
                
                String studentJson = JSON.serialize(requestMap.get('student'));
                System.debug('studentJson---'+ studentJson);
                EMXWebServiceWrapper.student student = (EMXWebServiceWrapper.student) JSON.deserialize(studentJson, EMXWebServiceWrapper.student.class);
                System.debug('student---'+ student);

                List<String> missingFields = new List<String>();
                if(String.isBlank(student.name)) missingFields.add('name');
                if(String.isBlank(student.nricOrPassportNo)) missingFields.add('nricOrPassportNo');
                if(String.isBlank(student.dateOfBirth)) missingFields.add('dateOfBirth');
                //if(String.isBlank(student.CRMHouseholdID)) missingFields.add('CRMHouseholdID');

                if(!missingFields.isEmpty()){
                    throw new MyException('The required field(s) are missing for Student: ' + String.join(missingFields, ', '));
                }
                
                Boolean isDOB = String.isNotBlank(student.dateOfBirth) ? checkDateFormat(student.dateOfBirth) : true;
                Boolean isPassExpire = String.isNotBlank(student.passportExpiryDate) ? checkDateFormat(student.passportExpiryDate) : true;
                
                isUpdate = isDOB && isPassExpire;
                System.debug('isUpdate---'+ isUpdate);
                
                if(isUpdate){
                    if(String.isNotBlank(student.CRMStudentID)){
                        /*List<Account> parentAcc = new List<Account>();
                        List<Contact> parentCon = new List<Contact>();
                        if (String.isNotBlank(student.CRMHouseholdID)) {
                            parentAcc = [SELECT Id FROM Account WHERE Id =: student.CRMHouseholdID LIMIT 1];
                            if(parentAcc.isEmpty()){
                                throw new MyException('Record not found for the provided CRMHouseholdID. Please enter a valid CRMHouseholdID');
                            }else{
                                parentCon = [SELECT Id, Primary_Account__c FROM Contact WHERE Primary_Account__c = :student.CRMHouseholdID AND Primary_Contact__c = TRUE LIMIT 1];

                            }
                        }*/
                        
                        List<Student__c> stud = [SELECT Id, Student_SFID__c, Student_UID__c, EMX_ID__c, Name, Preferred_Name__c, NRIC_Passport_No__c, 
                                                 Passport_Expiry_Date__c, Date_of_Birth__c, Nationality__c, Citizenship__c, Gender__c, Marital_Status__c, Race__c, 
                                                 Religion__c, Student_Mobile_No__c, Email_Address__c, Street_m__c, Postcode_m__c, City_m__c, State_m__c, Country_m__c, 
                                                 Contact_Telephone_No_m__c, Street_p__c, Postcode_p__c, City_p__c, State_p__c, Country_p__c, Contact_Telephone_No_p__c, 
                                                 Parent_Account__c, Primary_Contact__c FROM Student__c WHERE Id =: student.CRMStudentID LIMIT 1];
                        if(!stud.isEmpty()){
                            
                            //stud[0].Student_SFID__c = String.isNotBlank(student.studentSFID) ? student.studentSFID : stud[0].Student_SFID__c;
                            stud[0].Student_UID__c = String.isNotBlank(student.studentUID) ? student.studentUID : stud[0].Student_UID__c;
                            stud[0].EMX_ID__c = String.isNotBlank(student.EMXID) ? student.EMXID : stud[0].EMX_ID__c;
                            stud[0].Name = String.isNotBlank(student.name) ? student.name : stud[0].Name;
                            stud[0].Preferred_Name__c = String.isNotBlank(student.preferredName) ? student.preferredName : stud[0].Preferred_Name__c;
                            stud[0].NRIC_Passport_No__c = String.isNotBlank(student.nricOrPassportNo) ? student.nricOrPassportNo : stud[0].NRIC_Passport_No__c;
                            stud[0].Passport_Expiry_Date__c = String.isNotBlank(student.passportExpiryDate) ? Date.valueOf(student.passportExpiryDate) : stud[0].Passport_Expiry_Date__c;
                            stud[0].Date_of_Birth__c = String.isNotBlank(student.dateOfBirth) ? Date.valueOf(student.dateOfBirth) : stud[0].Date_of_Birth__c;
                            stud[0].Nationality__c = String.isNotBlank(student.nationality) ? student.nationality : stud[0].Nationality__c;
                            //stud[0].Citizenship__c = String.isNotBlank(student.citizenship) ? student.citizenship : stud[0].Citizenship__c;
                            stud[0].Gender__c = String.isNotBlank(student.gender) ? student.gender : stud[0].Gender__c;
                            stud[0].Marital_Status__c = String.isNotBlank(student.maritalStatus) ? student.maritalStatus : stud[0].Marital_Status__c;
                            stud[0].Race__c = String.isNotBlank(student.race) ? student.race : stud[0].Race__c;
                            stud[0].Religion__c = String.isNotBlank(student.religion) ? student.religion : stud[0].Religion__c;
                            stud[0].Student_Mobile_No__c = String.isNotBlank(student.studentMobileNo) ? student.studentMobileNo : stud[0].Student_Mobile_No__c;
                            stud[0].Email_Address__c = String.isNotBlank(student.emailAddress) ? student.emailAddress : stud[0].Email_Address__c;
                            stud[0].Street_m__c = String.isNotBlank(student.mailingStreet) ? student.mailingStreet : stud[0].Street_m__c;
                            stud[0].Postcode_m__c = String.isNotBlank(student.mailingPostCode) ? student.mailingPostCode : stud[0].Postcode_m__c;
                            stud[0].City_m__c = String.isNotBlank(student.mailingCity) ? student.mailingCity : stud[0].City_m__c;
                            stud[0].State_m__c = String.isNotBlank(student.mailingState) ? student.mailingState : stud[0].State_m__c;
                            stud[0].Country_m__c = String.isNotBlank(student.mailingCountry) ? student.mailingCountry : stud[0].Country_m__c;
                            stud[0].Contact_Telephone_No_m__c = String.isNotBlank(student.mailingConTelNo) ? student.mailingConTelNo : stud[0].Contact_Telephone_No_m__c;
                            stud[0].Street_p__c = String.isNotBlank(student.permanentStreet) ? student.permanentStreet : stud[0].Street_p__c;
                            stud[0].Postcode_p__c = String.isNotBlank(student.permanentPostCode) ? student.permanentPostCode : stud[0].Postcode_p__c;
                            stud[0].City_p__c = String.isNotBlank(student.permanentCity) ? student.permanentCity : stud[0].City_p__c;
                            stud[0].State_p__c = String.isNotBlank(student.permanentState) ? student.permanentState : stud[0].State_p__c;
                            stud[0].Country_p__c = String.isNotBlank(student.permanentCountry) ? student.permanentCountry : stud[0].Country_p__c;
                            stud[0].Contact_Telephone_No_p__c = String.isNotBlank(student.permanentConTelNo) ? student.permanentConTelNo : stud[0].Contact_Telephone_No_p__c;
                            /*if(!parentAcc.isEmpty()){
                                if(stud[0].Parent_Account__c == parentAcc[0].Id){
                                    stud[0].Parent_Account__c = parentAcc[0].Id;
                                }else{
                                    throw new MyException('The parent account for the student cannot be changed.');
                                }
                            }
                            if(!parentCon.isEmpty()){
                                    stud[0].Primary_Contact__c = parentCon[0].Id != null ? parentCon[0].Id : null;
                            }*/
                            
                            update stud;
                            System.debug('Student with existing Salesforce Id---'+ stud[0].Id);
                            res.statusCode = 200;
                            student.studentStatus = 'Student record updated successfully.';
                            resultMsg.put('body', student);
                            resultMap.put('success',resultMsg);
                            String responseBody = JSON.serialize(resultMap);
                            res.responseBody = Blob.valueOf(responseBody);
                            SISIntegrationLog.createLog(req.requestBody.toString(),responseBody,'Success');
                        }else{
                            throw new MyException('CRMStudentID not have a matching record. Please enter a valid CRMStudentID.');
                        }
                    }else{
                        throw new MyException('CRMStudentID is mandatory to update. Please enter CRMStudentID.');
                    }
                }else{
                    throw new MyException('If dateOfBirth or passportExpiryDate entered, It should be in the format (yyyy-mm-dd).');
                }
            }
            
        }catch(MyException e){
            res.statusCode = 400;
            resultMsg.put('studentStatus',string.valueOf(e.getMessage()));
            resultMap.put('error',resultMsg);
            String responseBody = JSON.serialize(resultMap);
            res.responseBody = Blob.valueOf(responseBody);
            SISIntegrationLog.createLog(req.requestBody.toString(),responseBody,'Failure');
            system.debug('res.responseBody---'+res.responseBody.toString());
        }catch(Exception e){
            System.debug('Error---'+ e.getStackTraceString()+ e.getTypeName());
            if (e.getTypeName() == 'System.DmlException') {
                resultMsg.put('studentStatus', string.valueOf(e.getDmlMessage(0)));
            } else {
                resultMsg.put('studentStatus', string.valueOf(e.getMessage()));
            }
            res.statusCode = 400;
            resultMap.put('error', resultMsg);
            String responseBody = JSON.serialize(resultMap);
            res.responseBody = Blob.valueOf(responseBody);
            SISIntegrationLog.createLog(req.requestBody.toString(),responseBody,'Failure');
            System.debug('res.responseBody---' + res.responseBody.toString());
        }
        
    }
    
    public static Boolean checkDateFormat(String dateToCheck){
        String datePattern = '^\\d{4}-\\d{2}-\\d{2}$';
        return Pattern.matches(datePattern, dateToCheck);
    }
}